// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/smartcontractkit/chainlink-ccv/indexer/pkg/common"

	mock "github.com/stretchr/testify/mock"
)

// MockMessageSubscriber is an autogenerated mock type for the MessageSubscriber type
type MockMessageSubscriber struct {
	mock.Mock
}

type MockMessageSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageSubscriber) EXPECT() *MockMessageSubscriber_Expecter {
	return &MockMessageSubscriber_Expecter{mock: &_m.Mock}
}

// IsRunning provides a mock function with no fields
func (_m *MockMessageSubscriber) IsRunning() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMessageSubscriber_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockMessageSubscriber_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockMessageSubscriber_Expecter) IsRunning() *MockMessageSubscriber_IsRunning_Call {
	return &MockMessageSubscriber_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockMessageSubscriber_IsRunning_Call) Run(run func()) *MockMessageSubscriber_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageSubscriber_IsRunning_Call) Return(_a0 bool) *MockMessageSubscriber_IsRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageSubscriber_IsRunning_Call) RunAndReturn(run func() bool) *MockMessageSubscriber_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockMessageSubscriber) Start(ctx context.Context) (<-chan common.MessageWithMetadata, <-chan error, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 <-chan common.MessageWithMetadata
	var r1 <-chan error
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan common.MessageWithMetadata, <-chan error, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan common.MessageWithMetadata); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan common.MessageWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) <-chan error); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMessageSubscriber_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockMessageSubscriber_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMessageSubscriber_Expecter) Start(ctx interface{}) *MockMessageSubscriber_Start_Call {
	return &MockMessageSubscriber_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockMessageSubscriber_Start_Call) Run(run func(ctx context.Context)) *MockMessageSubscriber_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMessageSubscriber_Start_Call) Return(_a0 <-chan common.MessageWithMetadata, _a1 <-chan error, _a2 error) *MockMessageSubscriber_Start_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMessageSubscriber_Start_Call) RunAndReturn(run func(context.Context) (<-chan common.MessageWithMetadata, <-chan error, error)) *MockMessageSubscriber_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageSubscriber creates a new instance of MockMessageSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSubscriber {
	mock := &MockMessageSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
