// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFinalityViolationChecker is an autogenerated mock type for the FinalityViolationChecker type
type MockFinalityViolationChecker struct {
	mock.Mock
}

type MockFinalityViolationChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinalityViolationChecker) EXPECT() *MockFinalityViolationChecker_Expecter {
	return &MockFinalityViolationChecker_Expecter{mock: &_m.Mock}
}

// IsFinalityViolated provides a mock function with no fields
func (_m *MockFinalityViolationChecker) IsFinalityViolated() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsFinalityViolated")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockFinalityViolationChecker_IsFinalityViolated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFinalityViolated'
type MockFinalityViolationChecker_IsFinalityViolated_Call struct {
	*mock.Call
}

// IsFinalityViolated is a helper method to define mock.On call
func (_e *MockFinalityViolationChecker_Expecter) IsFinalityViolated() *MockFinalityViolationChecker_IsFinalityViolated_Call {
	return &MockFinalityViolationChecker_IsFinalityViolated_Call{Call: _e.mock.On("IsFinalityViolated")}
}

func (_c *MockFinalityViolationChecker_IsFinalityViolated_Call) Run(run func()) *MockFinalityViolationChecker_IsFinalityViolated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFinalityViolationChecker_IsFinalityViolated_Call) Return(_a0 bool) *MockFinalityViolationChecker_IsFinalityViolated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFinalityViolationChecker_IsFinalityViolated_Call) RunAndReturn(run func() bool) *MockFinalityViolationChecker_IsFinalityViolated_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFinalized provides a mock function with given fields: ctx, finalizedBlock
func (_m *MockFinalityViolationChecker) UpdateFinalized(ctx context.Context, finalizedBlock uint64) error {
	ret := _m.Called(ctx, finalizedBlock)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFinalized")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, finalizedBlock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFinalityViolationChecker_UpdateFinalized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFinalized'
type MockFinalityViolationChecker_UpdateFinalized_Call struct {
	*mock.Call
}

// UpdateFinalized is a helper method to define mock.On call
//   - ctx context.Context
//   - finalizedBlock uint64
func (_e *MockFinalityViolationChecker_Expecter) UpdateFinalized(ctx interface{}, finalizedBlock interface{}) *MockFinalityViolationChecker_UpdateFinalized_Call {
	return &MockFinalityViolationChecker_UpdateFinalized_Call{Call: _e.mock.On("UpdateFinalized", ctx, finalizedBlock)}
}

func (_c *MockFinalityViolationChecker_UpdateFinalized_Call) Run(run func(ctx context.Context, finalizedBlock uint64)) *MockFinalityViolationChecker_UpdateFinalized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockFinalityViolationChecker_UpdateFinalized_Call) Return(_a0 error) *MockFinalityViolationChecker_UpdateFinalized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFinalityViolationChecker_UpdateFinalized_Call) RunAndReturn(run func(context.Context, uint64) error) *MockFinalityViolationChecker_UpdateFinalized_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFinalityViolationChecker creates a new instance of MockFinalityViolationChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinalityViolationChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinalityViolationChecker {
	mock := &MockFinalityViolationChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
