// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	big "math/big"

	context "context"

	protocol "github.com/smartcontractkit/chainlink-ccv/protocol"
	mock "github.com/stretchr/testify/mock"
)

// MockSourceReader is an autogenerated mock type for the SourceReader type
type MockSourceReader struct {
	mock.Mock
}

type MockSourceReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceReader) EXPECT() *MockSourceReader_Expecter {
	return &MockSourceReader_Expecter{mock: &_m.Mock}
}

// FetchMessageSentEvents provides a mock function with given fields: ctx, fromBlock, toBlock
func (_m *MockSourceReader) FetchMessageSentEvents(ctx context.Context, fromBlock *big.Int, toBlock *big.Int) ([]protocol.MessageSentEvent, error) {
	ret := _m.Called(ctx, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for FetchMessageSentEvents")
	}

	var r0 []protocol.MessageSentEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int, *big.Int) ([]protocol.MessageSentEvent, error)); ok {
		return rf(ctx, fromBlock, toBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int, *big.Int) []protocol.MessageSentEvent); ok {
		r0 = rf(ctx, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]protocol.MessageSentEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *big.Int, *big.Int) error); ok {
		r1 = rf(ctx, fromBlock, toBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceReader_FetchMessageSentEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMessageSentEvents'
type MockSourceReader_FetchMessageSentEvents_Call struct {
	*mock.Call
}

// FetchMessageSentEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock *big.Int
//   - toBlock *big.Int
func (_e *MockSourceReader_Expecter) FetchMessageSentEvents(ctx interface{}, fromBlock interface{}, toBlock interface{}) *MockSourceReader_FetchMessageSentEvents_Call {
	return &MockSourceReader_FetchMessageSentEvents_Call{Call: _e.mock.On("FetchMessageSentEvents", ctx, fromBlock, toBlock)}
}

func (_c *MockSourceReader_FetchMessageSentEvents_Call) Run(run func(ctx context.Context, fromBlock *big.Int, toBlock *big.Int)) *MockSourceReader_FetchMessageSentEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*big.Int), args[2].(*big.Int))
	})
	return _c
}

func (_c *MockSourceReader_FetchMessageSentEvents_Call) Return(_a0 []protocol.MessageSentEvent, _a1 error) *MockSourceReader_FetchMessageSentEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceReader_FetchMessageSentEvents_Call) RunAndReturn(run func(context.Context, *big.Int, *big.Int) ([]protocol.MessageSentEvent, error)) *MockSourceReader_FetchMessageSentEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocksHeaders provides a mock function with given fields: ctx, blockNumber
func (_m *MockSourceReader) GetBlocksHeaders(ctx context.Context, blockNumber []*big.Int) (map[*big.Int]protocol.BlockHeader, error) {
	ret := _m.Called(ctx, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocksHeaders")
	}

	var r0 map[*big.Int]protocol.BlockHeader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*big.Int) (map[*big.Int]protocol.BlockHeader, error)); ok {
		return rf(ctx, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*big.Int) map[*big.Int]protocol.BlockHeader); ok {
		r0 = rf(ctx, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[*big.Int]protocol.BlockHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*big.Int) error); ok {
		r1 = rf(ctx, blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceReader_GetBlocksHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocksHeaders'
type MockSourceReader_GetBlocksHeaders_Call struct {
	*mock.Call
}

// GetBlocksHeaders is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber []*big.Int
func (_e *MockSourceReader_Expecter) GetBlocksHeaders(ctx interface{}, blockNumber interface{}) *MockSourceReader_GetBlocksHeaders_Call {
	return &MockSourceReader_GetBlocksHeaders_Call{Call: _e.mock.On("GetBlocksHeaders", ctx, blockNumber)}
}

func (_c *MockSourceReader_GetBlocksHeaders_Call) Run(run func(ctx context.Context, blockNumber []*big.Int)) *MockSourceReader_GetBlocksHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*big.Int))
	})
	return _c
}

func (_c *MockSourceReader_GetBlocksHeaders_Call) Return(_a0 map[*big.Int]protocol.BlockHeader, _a1 error) *MockSourceReader_GetBlocksHeaders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceReader_GetBlocksHeaders_Call) RunAndReturn(run func(context.Context, []*big.Int) (map[*big.Int]protocol.BlockHeader, error)) *MockSourceReader_GetBlocksHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// GetRMNCursedSubjects provides a mock function with given fields: ctx
func (_m *MockSourceReader) GetRMNCursedSubjects(ctx context.Context) ([]protocol.Bytes16, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRMNCursedSubjects")
	}

	var r0 []protocol.Bytes16
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]protocol.Bytes16, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []protocol.Bytes16); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]protocol.Bytes16)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceReader_GetRMNCursedSubjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRMNCursedSubjects'
type MockSourceReader_GetRMNCursedSubjects_Call struct {
	*mock.Call
}

// GetRMNCursedSubjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSourceReader_Expecter) GetRMNCursedSubjects(ctx interface{}) *MockSourceReader_GetRMNCursedSubjects_Call {
	return &MockSourceReader_GetRMNCursedSubjects_Call{Call: _e.mock.On("GetRMNCursedSubjects", ctx)}
}

func (_c *MockSourceReader_GetRMNCursedSubjects_Call) Run(run func(ctx context.Context)) *MockSourceReader_GetRMNCursedSubjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSourceReader_GetRMNCursedSubjects_Call) Return(_a0 []protocol.Bytes16, _a1 error) *MockSourceReader_GetRMNCursedSubjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceReader_GetRMNCursedSubjects_Call) RunAndReturn(run func(context.Context) ([]protocol.Bytes16, error)) *MockSourceReader_GetRMNCursedSubjects_Call {
	_c.Call.Return(run)
	return _c
}

// LatestAndFinalizedBlock provides a mock function with given fields: ctx
func (_m *MockSourceReader) LatestAndFinalizedBlock(ctx context.Context) (*protocol.BlockHeader, *protocol.BlockHeader, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LatestAndFinalizedBlock")
	}

	var r0 *protocol.BlockHeader
	var r1 *protocol.BlockHeader
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (*protocol.BlockHeader, *protocol.BlockHeader, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *protocol.BlockHeader); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protocol.BlockHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *protocol.BlockHeader); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*protocol.BlockHeader)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSourceReader_LatestAndFinalizedBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestAndFinalizedBlock'
type MockSourceReader_LatestAndFinalizedBlock_Call struct {
	*mock.Call
}

// LatestAndFinalizedBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSourceReader_Expecter) LatestAndFinalizedBlock(ctx interface{}) *MockSourceReader_LatestAndFinalizedBlock_Call {
	return &MockSourceReader_LatestAndFinalizedBlock_Call{Call: _e.mock.On("LatestAndFinalizedBlock", ctx)}
}

func (_c *MockSourceReader_LatestAndFinalizedBlock_Call) Run(run func(ctx context.Context)) *MockSourceReader_LatestAndFinalizedBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSourceReader_LatestAndFinalizedBlock_Call) Return(latest *protocol.BlockHeader, finalized *protocol.BlockHeader, err error) *MockSourceReader_LatestAndFinalizedBlock_Call {
	_c.Call.Return(latest, finalized, err)
	return _c
}

func (_c *MockSourceReader_LatestAndFinalizedBlock_Call) RunAndReturn(run func(context.Context) (*protocol.BlockHeader, *protocol.BlockHeader, error)) *MockSourceReader_LatestAndFinalizedBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSourceReader creates a new instance of MockSourceReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceReader {
	mock := &MockSourceReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
