// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/smartcontractkit/chainlink-ccv/indexer/pkg/common"

	mock "github.com/stretchr/testify/mock"

	protocol "github.com/smartcontractkit/chainlink-ccv/protocol"
)

// MockIndexerStorage is an autogenerated mock type for the IndexerStorage type
type MockIndexerStorage struct {
	mock.Mock
}

type MockIndexerStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexerStorage) EXPECT() *MockIndexerStorage_Expecter {
	return &MockIndexerStorage_Expecter{mock: &_m.Mock}
}

// CreateDiscoveryState provides a mock function with given fields: ctx, discoveryLocation, startingSequenceNumber
func (_m *MockIndexerStorage) CreateDiscoveryState(ctx context.Context, discoveryLocation string, startingSequenceNumber int) error {
	ret := _m.Called(ctx, discoveryLocation, startingSequenceNumber)

	if len(ret) == 0 {
		panic("no return value specified for CreateDiscoveryState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, discoveryLocation, startingSequenceNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexerStorage_CreateDiscoveryState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDiscoveryState'
type MockIndexerStorage_CreateDiscoveryState_Call struct {
	*mock.Call
}

// CreateDiscoveryState is a helper method to define mock.On call
//   - ctx context.Context
//   - discoveryLocation string
//   - startingSequenceNumber int
func (_e *MockIndexerStorage_Expecter) CreateDiscoveryState(ctx interface{}, discoveryLocation interface{}, startingSequenceNumber interface{}) *MockIndexerStorage_CreateDiscoveryState_Call {
	return &MockIndexerStorage_CreateDiscoveryState_Call{Call: _e.mock.On("CreateDiscoveryState", ctx, discoveryLocation, startingSequenceNumber)}
}

func (_c *MockIndexerStorage_CreateDiscoveryState_Call) Run(run func(ctx context.Context, discoveryLocation string, startingSequenceNumber int)) *MockIndexerStorage_CreateDiscoveryState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockIndexerStorage_CreateDiscoveryState_Call) Return(_a0 error) *MockIndexerStorage_CreateDiscoveryState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexerStorage_CreateDiscoveryState_Call) RunAndReturn(run func(context.Context, string, int) error) *MockIndexerStorage_CreateDiscoveryState_Call {
	_c.Call.Return(run)
	return _c
}

// GetCCVData provides a mock function with given fields: ctx, messageID
func (_m *MockIndexerStorage) GetCCVData(ctx context.Context, messageID protocol.Bytes32) ([]common.VerifierResultWithMetadata, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetCCVData")
	}

	var r0 []common.VerifierResultWithMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Bytes32) ([]common.VerifierResultWithMetadata, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Bytes32) []common.VerifierResultWithMetadata); ok {
		r0 = rf(ctx, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.VerifierResultWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.Bytes32) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexerStorage_GetCCVData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCCVData'
type MockIndexerStorage_GetCCVData_Call struct {
	*mock.Call
}

// GetCCVData is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID protocol.Bytes32
func (_e *MockIndexerStorage_Expecter) GetCCVData(ctx interface{}, messageID interface{}) *MockIndexerStorage_GetCCVData_Call {
	return &MockIndexerStorage_GetCCVData_Call{Call: _e.mock.On("GetCCVData", ctx, messageID)}
}

func (_c *MockIndexerStorage_GetCCVData_Call) Run(run func(ctx context.Context, messageID protocol.Bytes32)) *MockIndexerStorage_GetCCVData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.Bytes32))
	})
	return _c
}

func (_c *MockIndexerStorage_GetCCVData_Call) Return(_a0 []common.VerifierResultWithMetadata, _a1 error) *MockIndexerStorage_GetCCVData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexerStorage_GetCCVData_Call) RunAndReturn(run func(context.Context, protocol.Bytes32) ([]common.VerifierResultWithMetadata, error)) *MockIndexerStorage_GetCCVData_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiscoverySequenceNumber provides a mock function with given fields: ctx, discoveryLocation
func (_m *MockIndexerStorage) GetDiscoverySequenceNumber(ctx context.Context, discoveryLocation string) (int, error) {
	ret := _m.Called(ctx, discoveryLocation)

	if len(ret) == 0 {
		panic("no return value specified for GetDiscoverySequenceNumber")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, discoveryLocation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, discoveryLocation)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, discoveryLocation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexerStorage_GetDiscoverySequenceNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiscoverySequenceNumber'
type MockIndexerStorage_GetDiscoverySequenceNumber_Call struct {
	*mock.Call
}

// GetDiscoverySequenceNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - discoveryLocation string
func (_e *MockIndexerStorage_Expecter) GetDiscoverySequenceNumber(ctx interface{}, discoveryLocation interface{}) *MockIndexerStorage_GetDiscoverySequenceNumber_Call {
	return &MockIndexerStorage_GetDiscoverySequenceNumber_Call{Call: _e.mock.On("GetDiscoverySequenceNumber", ctx, discoveryLocation)}
}

func (_c *MockIndexerStorage_GetDiscoverySequenceNumber_Call) Run(run func(ctx context.Context, discoveryLocation string)) *MockIndexerStorage_GetDiscoverySequenceNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIndexerStorage_GetDiscoverySequenceNumber_Call) Return(_a0 int, _a1 error) *MockIndexerStorage_GetDiscoverySequenceNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexerStorage_GetDiscoverySequenceNumber_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockIndexerStorage_GetDiscoverySequenceNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function with given fields: ctx, messageID
func (_m *MockIndexerStorage) GetMessage(ctx context.Context, messageID protocol.Bytes32) (common.MessageWithMetadata, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 common.MessageWithMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Bytes32) (common.MessageWithMetadata, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Bytes32) common.MessageWithMetadata); ok {
		r0 = rf(ctx, messageID)
	} else {
		r0 = ret.Get(0).(common.MessageWithMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.Bytes32) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexerStorage_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type MockIndexerStorage_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID protocol.Bytes32
func (_e *MockIndexerStorage_Expecter) GetMessage(ctx interface{}, messageID interface{}) *MockIndexerStorage_GetMessage_Call {
	return &MockIndexerStorage_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx, messageID)}
}

func (_c *MockIndexerStorage_GetMessage_Call) Run(run func(ctx context.Context, messageID protocol.Bytes32)) *MockIndexerStorage_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.Bytes32))
	})
	return _c
}

func (_c *MockIndexerStorage_GetMessage_Call) Return(_a0 common.MessageWithMetadata, _a1 error) *MockIndexerStorage_GetMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexerStorage_GetMessage_Call) RunAndReturn(run func(context.Context, protocol.Bytes32) (common.MessageWithMetadata, error)) *MockIndexerStorage_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMessages provides a mock function with given fields: ctx, messages
func (_m *MockIndexerStorage) InsertMessages(ctx context.Context, messages []common.MessageWithMetadata) error {
	ret := _m.Called(ctx, messages)

	if len(ret) == 0 {
		panic("no return value specified for InsertMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []common.MessageWithMetadata) error); ok {
		r0 = rf(ctx, messages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexerStorage_InsertMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMessages'
type MockIndexerStorage_InsertMessages_Call struct {
	*mock.Call
}

// InsertMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []common.MessageWithMetadata
func (_e *MockIndexerStorage_Expecter) InsertMessages(ctx interface{}, messages interface{}) *MockIndexerStorage_InsertMessages_Call {
	return &MockIndexerStorage_InsertMessages_Call{Call: _e.mock.On("InsertMessages", ctx, messages)}
}

func (_c *MockIndexerStorage_InsertMessages_Call) Run(run func(ctx context.Context, messages []common.MessageWithMetadata)) *MockIndexerStorage_InsertMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]common.MessageWithMetadata))
	})
	return _c
}

func (_c *MockIndexerStorage_InsertMessages_Call) Return(_a0 error) *MockIndexerStorage_InsertMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexerStorage_InsertMessages_Call) RunAndReturn(run func(context.Context, []common.MessageWithMetadata) error) *MockIndexerStorage_InsertMessages_Call {
	_c.Call.Return(run)
	return _c
}

// InsertVerifierResults provides a mock function with given fields: ctx, verifierResults
func (_m *MockIndexerStorage) InsertVerifierResults(ctx context.Context, verifierResults []common.VerifierResultWithMetadata) error {
	ret := _m.Called(ctx, verifierResults)

	if len(ret) == 0 {
		panic("no return value specified for InsertVerifierResults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []common.VerifierResultWithMetadata) error); ok {
		r0 = rf(ctx, verifierResults)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexerStorage_InsertVerifierResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertVerifierResults'
type MockIndexerStorage_InsertVerifierResults_Call struct {
	*mock.Call
}

// InsertVerifierResults is a helper method to define mock.On call
//   - ctx context.Context
//   - verifierResults []common.VerifierResultWithMetadata
func (_e *MockIndexerStorage_Expecter) InsertVerifierResults(ctx interface{}, verifierResults interface{}) *MockIndexerStorage_InsertVerifierResults_Call {
	return &MockIndexerStorage_InsertVerifierResults_Call{Call: _e.mock.On("InsertVerifierResults", ctx, verifierResults)}
}

func (_c *MockIndexerStorage_InsertVerifierResults_Call) Run(run func(ctx context.Context, verifierResults []common.VerifierResultWithMetadata)) *MockIndexerStorage_InsertVerifierResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]common.VerifierResultWithMetadata))
	})
	return _c
}

func (_c *MockIndexerStorage_InsertVerifierResults_Call) Return(_a0 error) *MockIndexerStorage_InsertVerifierResults_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexerStorage_InsertVerifierResults_Call) RunAndReturn(run func(context.Context, []common.VerifierResultWithMetadata) error) *MockIndexerStorage_InsertVerifierResults_Call {
	_c.Call.Return(run)
	return _c
}

// PersistDiscoveryBatch provides a mock function with given fields: ctx, batch
func (_m *MockIndexerStorage) PersistDiscoveryBatch(ctx context.Context, batch common.DiscoveryBatch) error {
	ret := _m.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for PersistDiscoveryBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.DiscoveryBatch) error); ok {
		r0 = rf(ctx, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexerStorage_PersistDiscoveryBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistDiscoveryBatch'
type MockIndexerStorage_PersistDiscoveryBatch_Call struct {
	*mock.Call
}

// PersistDiscoveryBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - batch common.DiscoveryBatch
func (_e *MockIndexerStorage_Expecter) PersistDiscoveryBatch(ctx interface{}, batch interface{}) *MockIndexerStorage_PersistDiscoveryBatch_Call {
	return &MockIndexerStorage_PersistDiscoveryBatch_Call{Call: _e.mock.On("PersistDiscoveryBatch", ctx, batch)}
}

func (_c *MockIndexerStorage_PersistDiscoveryBatch_Call) Run(run func(ctx context.Context, batch common.DiscoveryBatch)) *MockIndexerStorage_PersistDiscoveryBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.DiscoveryBatch))
	})
	return _c
}

func (_c *MockIndexerStorage_PersistDiscoveryBatch_Call) Return(_a0 error) *MockIndexerStorage_PersistDiscoveryBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexerStorage_PersistDiscoveryBatch_Call) RunAndReturn(run func(context.Context, common.DiscoveryBatch) error) *MockIndexerStorage_PersistDiscoveryBatch_Call {
	_c.Call.Return(run)
	return _c
}

// QueryCCVData provides a mock function with given fields: ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset
func (_m *MockIndexerStorage) QueryCCVData(ctx context.Context, start int64, end int64, sourceChainSelectors []protocol.ChainSelector, destChainSelectors []protocol.ChainSelector, limit uint64, offset uint64) (map[string][]common.VerifierResultWithMetadata, error) {
	ret := _m.Called(ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for QueryCCVData")
	}

	var r0 map[string][]common.VerifierResultWithMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, []protocol.ChainSelector, []protocol.ChainSelector, uint64, uint64) (map[string][]common.VerifierResultWithMetadata, error)); ok {
		return rf(ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, []protocol.ChainSelector, []protocol.ChainSelector, uint64, uint64) map[string][]common.VerifierResultWithMetadata); ok {
		r0 = rf(ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]common.VerifierResultWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, []protocol.ChainSelector, []protocol.ChainSelector, uint64, uint64) error); ok {
		r1 = rf(ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexerStorage_QueryCCVData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryCCVData'
type MockIndexerStorage_QueryCCVData_Call struct {
	*mock.Call
}

// QueryCCVData is a helper method to define mock.On call
//   - ctx context.Context
//   - start int64
//   - end int64
//   - sourceChainSelectors []protocol.ChainSelector
//   - destChainSelectors []protocol.ChainSelector
//   - limit uint64
//   - offset uint64
func (_e *MockIndexerStorage_Expecter) QueryCCVData(ctx interface{}, start interface{}, end interface{}, sourceChainSelectors interface{}, destChainSelectors interface{}, limit interface{}, offset interface{}) *MockIndexerStorage_QueryCCVData_Call {
	return &MockIndexerStorage_QueryCCVData_Call{Call: _e.mock.On("QueryCCVData", ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)}
}

func (_c *MockIndexerStorage_QueryCCVData_Call) Run(run func(ctx context.Context, start int64, end int64, sourceChainSelectors []protocol.ChainSelector, destChainSelectors []protocol.ChainSelector, limit uint64, offset uint64)) *MockIndexerStorage_QueryCCVData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].([]protocol.ChainSelector), args[4].([]protocol.ChainSelector), args[5].(uint64), args[6].(uint64))
	})
	return _c
}

func (_c *MockIndexerStorage_QueryCCVData_Call) Return(_a0 map[string][]common.VerifierResultWithMetadata, _a1 error) *MockIndexerStorage_QueryCCVData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexerStorage_QueryCCVData_Call) RunAndReturn(run func(context.Context, int64, int64, []protocol.ChainSelector, []protocol.ChainSelector, uint64, uint64) (map[string][]common.VerifierResultWithMetadata, error)) *MockIndexerStorage_QueryCCVData_Call {
	_c.Call.Return(run)
	return _c
}

// QueryMessages provides a mock function with given fields: ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset
func (_m *MockIndexerStorage) QueryMessages(ctx context.Context, start int64, end int64, sourceChainSelectors []protocol.ChainSelector, destChainSelectors []protocol.ChainSelector, limit uint64, offset uint64) ([]common.MessageWithMetadata, error) {
	ret := _m.Called(ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for QueryMessages")
	}

	var r0 []common.MessageWithMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, []protocol.ChainSelector, []protocol.ChainSelector, uint64, uint64) ([]common.MessageWithMetadata, error)); ok {
		return rf(ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, []protocol.ChainSelector, []protocol.ChainSelector, uint64, uint64) []common.MessageWithMetadata); ok {
		r0 = rf(ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.MessageWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, []protocol.ChainSelector, []protocol.ChainSelector, uint64, uint64) error); ok {
		r1 = rf(ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexerStorage_QueryMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryMessages'
type MockIndexerStorage_QueryMessages_Call struct {
	*mock.Call
}

// QueryMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - start int64
//   - end int64
//   - sourceChainSelectors []protocol.ChainSelector
//   - destChainSelectors []protocol.ChainSelector
//   - limit uint64
//   - offset uint64
func (_e *MockIndexerStorage_Expecter) QueryMessages(ctx interface{}, start interface{}, end interface{}, sourceChainSelectors interface{}, destChainSelectors interface{}, limit interface{}, offset interface{}) *MockIndexerStorage_QueryMessages_Call {
	return &MockIndexerStorage_QueryMessages_Call{Call: _e.mock.On("QueryMessages", ctx, start, end, sourceChainSelectors, destChainSelectors, limit, offset)}
}

func (_c *MockIndexerStorage_QueryMessages_Call) Run(run func(ctx context.Context, start int64, end int64, sourceChainSelectors []protocol.ChainSelector, destChainSelectors []protocol.ChainSelector, limit uint64, offset uint64)) *MockIndexerStorage_QueryMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].([]protocol.ChainSelector), args[4].([]protocol.ChainSelector), args[5].(uint64), args[6].(uint64))
	})
	return _c
}

func (_c *MockIndexerStorage_QueryMessages_Call) Return(_a0 []common.MessageWithMetadata, _a1 error) *MockIndexerStorage_QueryMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexerStorage_QueryMessages_Call) RunAndReturn(run func(context.Context, int64, int64, []protocol.ChainSelector, []protocol.ChainSelector, uint64, uint64) ([]common.MessageWithMetadata, error)) *MockIndexerStorage_QueryMessages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMessageStatus provides a mock function with given fields: ctx, messageID, status, lastErr
func (_m *MockIndexerStorage) UpdateMessageStatus(ctx context.Context, messageID protocol.Bytes32, status common.MessageStatus, lastErr string) error {
	ret := _m.Called(ctx, messageID, status, lastErr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessageStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Bytes32, common.MessageStatus, string) error); ok {
		r0 = rf(ctx, messageID, status, lastErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexerStorage_UpdateMessageStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessageStatus'
type MockIndexerStorage_UpdateMessageStatus_Call struct {
	*mock.Call
}

// UpdateMessageStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID protocol.Bytes32
//   - status common.MessageStatus
//   - lastErr string
func (_e *MockIndexerStorage_Expecter) UpdateMessageStatus(ctx interface{}, messageID interface{}, status interface{}, lastErr interface{}) *MockIndexerStorage_UpdateMessageStatus_Call {
	return &MockIndexerStorage_UpdateMessageStatus_Call{Call: _e.mock.On("UpdateMessageStatus", ctx, messageID, status, lastErr)}
}

func (_c *MockIndexerStorage_UpdateMessageStatus_Call) Run(run func(ctx context.Context, messageID protocol.Bytes32, status common.MessageStatus, lastErr string)) *MockIndexerStorage_UpdateMessageStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.Bytes32), args[2].(common.MessageStatus), args[3].(string))
	})
	return _c
}

func (_c *MockIndexerStorage_UpdateMessageStatus_Call) Return(_a0 error) *MockIndexerStorage_UpdateMessageStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexerStorage_UpdateMessageStatus_Call) RunAndReturn(run func(context.Context, protocol.Bytes32, common.MessageStatus, string) error) *MockIndexerStorage_UpdateMessageStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIndexerStorage creates a new instance of MockIndexerStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexerStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexerStorage {
	mock := &MockIndexerStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
