// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	protocol "github.com/smartcontractkit/chainlink-ccv/protocol"
	mock "github.com/stretchr/testify/mock"
)

// MockRMNCurseReader is an autogenerated mock type for the RMNCurseReader type
type MockRMNCurseReader struct {
	mock.Mock
}

type MockRMNCurseReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRMNCurseReader) EXPECT() *MockRMNCurseReader_Expecter {
	return &MockRMNCurseReader_Expecter{mock: &_m.Mock}
}

// GetRMNCursedSubjects provides a mock function with given fields: ctx
func (_m *MockRMNCurseReader) GetRMNCursedSubjects(ctx context.Context) ([]protocol.Bytes16, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRMNCursedSubjects")
	}

	var r0 []protocol.Bytes16
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]protocol.Bytes16, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []protocol.Bytes16); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]protocol.Bytes16)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRMNCurseReader_GetRMNCursedSubjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRMNCursedSubjects'
type MockRMNCurseReader_GetRMNCursedSubjects_Call struct {
	*mock.Call
}

// GetRMNCursedSubjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRMNCurseReader_Expecter) GetRMNCursedSubjects(ctx interface{}) *MockRMNCurseReader_GetRMNCursedSubjects_Call {
	return &MockRMNCurseReader_GetRMNCursedSubjects_Call{Call: _e.mock.On("GetRMNCursedSubjects", ctx)}
}

func (_c *MockRMNCurseReader_GetRMNCursedSubjects_Call) Run(run func(ctx context.Context)) *MockRMNCurseReader_GetRMNCursedSubjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRMNCurseReader_GetRMNCursedSubjects_Call) Return(_a0 []protocol.Bytes16, _a1 error) *MockRMNCurseReader_GetRMNCursedSubjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRMNCurseReader_GetRMNCursedSubjects_Call) RunAndReturn(run func(context.Context) ([]protocol.Bytes16, error)) *MockRMNCurseReader_GetRMNCursedSubjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRMNCurseReader creates a new instance of MockRMNCurseReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRMNCurseReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRMNCurseReader {
	mock := &MockRMNCurseReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
