// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessageRulesCheckerMetrics is an autogenerated mock type for the MessageRulesCheckerMetrics type
type MockMessageRulesCheckerMetrics struct {
	mock.Mock
}

type MockMessageRulesCheckerMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRulesCheckerMetrics) EXPECT() *MockMessageRulesCheckerMetrics_Expecter {
	return &MockMessageRulesCheckerMetrics_Expecter{mock: &_m.Mock}
}

// SetMessageDisablementRulesRefreshFailure provides a mock function with given fields: ctx, failed
func (_m *MockMessageRulesCheckerMetrics) SetMessageDisablementRulesRefreshFailure(ctx context.Context, failed int64) {
	_m.Called(ctx, failed)
}

// MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMessageDisablementRulesRefreshFailure'
type MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call struct {
	*mock.Call
}

// SetMessageDisablementRulesRefreshFailure is a helper method to define mock.On call
//   - ctx context.Context
//   - failed int64
func (_e *MockMessageRulesCheckerMetrics_Expecter) SetMessageDisablementRulesRefreshFailure(ctx interface{}, failed interface{}) *MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call {
	return &MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call{Call: _e.mock.On("SetMessageDisablementRulesRefreshFailure", ctx, failed)}
}

func (_c *MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call) Run(run func(ctx context.Context, failed int64)) *MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call) Return() *MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call) RunAndReturn(run func(context.Context, int64)) *MockMessageRulesCheckerMetrics_SetMessageDisablementRulesRefreshFailure_Call {
	_c.Run(run)
	return _c
}

// NewMockMessageRulesCheckerMetrics creates a new instance of MockMessageRulesCheckerMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRulesCheckerMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRulesCheckerMetrics {
	mock := &MockMessageRulesCheckerMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
