// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	common "github.com/smartcontractkit/chainlink-ccv/indexer/pkg/common"
	mock "github.com/stretchr/testify/mock"
)

// MockIndexerMetricLabeler is an autogenerated mock type for the IndexerMetricLabeler type
type MockIndexerMetricLabeler struct {
	mock.Mock
}

type MockIndexerMetricLabeler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexerMetricLabeler) EXPECT() *MockIndexerMetricLabeler_Expecter {
	return &MockIndexerMetricLabeler_Expecter{mock: &_m.Mock}
}

// DecrementActiveRequestsCounter provides a mock function with given fields: ctx
func (_m *MockIndexerMetricLabeler) DecrementActiveRequestsCounter(ctx context.Context) {
	_m.Called(ctx)
}

// MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementActiveRequestsCounter'
type MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call struct {
	*mock.Call
}

// DecrementActiveRequestsCounter is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexerMetricLabeler_Expecter) DecrementActiveRequestsCounter(ctx interface{}) *MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call {
	return &MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call{Call: _e.mock.On("DecrementActiveRequestsCounter", ctx)}
}

func (_c *MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call) Run(run func(ctx context.Context)) *MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call) Return() *MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call) RunAndReturn(run func(context.Context)) *MockIndexerMetricLabeler_DecrementActiveRequestsCounter_Call {
	_c.Run(run)
	return _c
}

// IncrementActiveRequestsCounter provides a mock function with given fields: ctx
func (_m *MockIndexerMetricLabeler) IncrementActiveRequestsCounter(ctx context.Context) {
	_m.Called(ctx)
}

// MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementActiveRequestsCounter'
type MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call struct {
	*mock.Call
}

// IncrementActiveRequestsCounter is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexerMetricLabeler_Expecter) IncrementActiveRequestsCounter(ctx interface{}) *MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call {
	return &MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call{Call: _e.mock.On("IncrementActiveRequestsCounter", ctx)}
}

func (_c *MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call) Run(run func(ctx context.Context)) *MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call) Return() *MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call) RunAndReturn(run func(context.Context)) *MockIndexerMetricLabeler_IncrementActiveRequestsCounter_Call {
	_c.Run(run)
	return _c
}

// IncrementUniqueMessagesCounter provides a mock function with given fields: ctx
func (_m *MockIndexerMetricLabeler) IncrementUniqueMessagesCounter(ctx context.Context) {
	_m.Called(ctx)
}

// MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementUniqueMessagesCounter'
type MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call struct {
	*mock.Call
}

// IncrementUniqueMessagesCounter is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexerMetricLabeler_Expecter) IncrementUniqueMessagesCounter(ctx interface{}) *MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call {
	return &MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call{Call: _e.mock.On("IncrementUniqueMessagesCounter", ctx)}
}

func (_c *MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call) Run(run func(ctx context.Context)) *MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call) Return() *MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call) RunAndReturn(run func(context.Context)) *MockIndexerMetricLabeler_IncrementUniqueMessagesCounter_Call {
	_c.Run(run)
	return _c
}

// IncrementVerificationRecordsCounter provides a mock function with given fields: ctx
func (_m *MockIndexerMetricLabeler) IncrementVerificationRecordsCounter(ctx context.Context) {
	_m.Called(ctx)
}

// MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementVerificationRecordsCounter'
type MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call struct {
	*mock.Call
}

// IncrementVerificationRecordsCounter is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexerMetricLabeler_Expecter) IncrementVerificationRecordsCounter(ctx interface{}) *MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call {
	return &MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call{Call: _e.mock.On("IncrementVerificationRecordsCounter", ctx)}
}

func (_c *MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call) Run(run func(ctx context.Context)) *MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call) Return() *MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call) RunAndReturn(run func(context.Context)) *MockIndexerMetricLabeler_IncrementVerificationRecordsCounter_Call {
	_c.Run(run)
	return _c
}

// RecordActiveReadersGauge provides a mock function with given fields: ctx, count
func (_m *MockIndexerMetricLabeler) RecordActiveReadersGauge(ctx context.Context, count int64) {
	_m.Called(ctx, count)
}

// MockIndexerMetricLabeler_RecordActiveReadersGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordActiveReadersGauge'
type MockIndexerMetricLabeler_RecordActiveReadersGauge_Call struct {
	*mock.Call
}

// RecordActiveReadersGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - count int64
func (_e *MockIndexerMetricLabeler_Expecter) RecordActiveReadersGauge(ctx interface{}, count interface{}) *MockIndexerMetricLabeler_RecordActiveReadersGauge_Call {
	return &MockIndexerMetricLabeler_RecordActiveReadersGauge_Call{Call: _e.mock.On("RecordActiveReadersGauge", ctx, count)}
}

func (_c *MockIndexerMetricLabeler_RecordActiveReadersGauge_Call) Run(run func(ctx context.Context, count int64)) *MockIndexerMetricLabeler_RecordActiveReadersGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordActiveReadersGauge_Call) Return() *MockIndexerMetricLabeler_RecordActiveReadersGauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordActiveReadersGauge_Call) RunAndReturn(run func(context.Context, int64)) *MockIndexerMetricLabeler_RecordActiveReadersGauge_Call {
	_c.Run(run)
	return _c
}

// RecordCircuitBreakerStatus provides a mock function with given fields: ctx, status
func (_m *MockIndexerMetricLabeler) RecordCircuitBreakerStatus(ctx context.Context, status bool) {
	_m.Called(ctx, status)
}

// MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCircuitBreakerStatus'
type MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call struct {
	*mock.Call
}

// RecordCircuitBreakerStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status bool
func (_e *MockIndexerMetricLabeler_Expecter) RecordCircuitBreakerStatus(ctx interface{}, status interface{}) *MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call {
	return &MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call{Call: _e.mock.On("RecordCircuitBreakerStatus", ctx, status)}
}

func (_c *MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call) Run(run func(ctx context.Context, status bool)) *MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call) Return() *MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call) RunAndReturn(run func(context.Context, bool)) *MockIndexerMetricLabeler_RecordCircuitBreakerStatus_Call {
	_c.Run(run)
	return _c
}

// RecordHTTPRequestDuration provides a mock function with given fields: ctx, duration, path, method, status
func (_m *MockIndexerMetricLabeler) RecordHTTPRequestDuration(ctx context.Context, duration time.Duration, path string, method string, status int) {
	_m.Called(ctx, duration, path, method, status)
}

// MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordHTTPRequestDuration'
type MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call struct {
	*mock.Call
}

// RecordHTTPRequestDuration is a helper method to define mock.On call
//   - ctx context.Context
//   - duration time.Duration
//   - path string
//   - method string
//   - status int
func (_e *MockIndexerMetricLabeler_Expecter) RecordHTTPRequestDuration(ctx interface{}, duration interface{}, path interface{}, method interface{}, status interface{}) *MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call {
	return &MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call{Call: _e.mock.On("RecordHTTPRequestDuration", ctx, duration, path, method, status)}
}

func (_c *MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call) Run(run func(ctx context.Context, duration time.Duration, path string, method string, status int)) *MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call) Return() *MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call) RunAndReturn(run func(context.Context, time.Duration, string, string, int)) *MockIndexerMetricLabeler_RecordHTTPRequestDuration_Call {
	_c.Run(run)
	return _c
}

// RecordIndexerMessageDiscoveryLatency provides a mock function with given fields: ctx, latency
func (_m *MockIndexerMetricLabeler) RecordIndexerMessageDiscoveryLatency(ctx context.Context, latency time.Duration) {
	_m.Called(ctx, latency)
}

// MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordIndexerMessageDiscoveryLatency'
type MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call struct {
	*mock.Call
}

// RecordIndexerMessageDiscoveryLatency is a helper method to define mock.On call
//   - ctx context.Context
//   - latency time.Duration
func (_e *MockIndexerMetricLabeler_Expecter) RecordIndexerMessageDiscoveryLatency(ctx interface{}, latency interface{}) *MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call {
	return &MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call{Call: _e.mock.On("RecordIndexerMessageDiscoveryLatency", ctx, latency)}
}

func (_c *MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call) Run(run func(ctx context.Context, latency time.Duration)) *MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call) Return() *MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call) RunAndReturn(run func(context.Context, time.Duration)) *MockIndexerMetricLabeler_RecordIndexerMessageDiscoveryLatency_Call {
	_c.Run(run)
	return _c
}

// RecordScannerPollingErrorsCounter provides a mock function with given fields: ctx
func (_m *MockIndexerMetricLabeler) RecordScannerPollingErrorsCounter(ctx context.Context) {
	_m.Called(ctx)
}

// MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordScannerPollingErrorsCounter'
type MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call struct {
	*mock.Call
}

// RecordScannerPollingErrorsCounter is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexerMetricLabeler_Expecter) RecordScannerPollingErrorsCounter(ctx interface{}) *MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call {
	return &MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call{Call: _e.mock.On("RecordScannerPollingErrorsCounter", ctx)}
}

func (_c *MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call) Run(run func(ctx context.Context)) *MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call) Return() *MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call) RunAndReturn(run func(context.Context)) *MockIndexerMetricLabeler_RecordScannerPollingErrorsCounter_Call {
	_c.Run(run)
	return _c
}

// RecordStorageInsertErrorsCounter provides a mock function with given fields: ctx, queryName
func (_m *MockIndexerMetricLabeler) RecordStorageInsertErrorsCounter(ctx context.Context, queryName string) {
	_m.Called(ctx, queryName)
}

// MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStorageInsertErrorsCounter'
type MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call struct {
	*mock.Call
}

// RecordStorageInsertErrorsCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - queryName string
func (_e *MockIndexerMetricLabeler_Expecter) RecordStorageInsertErrorsCounter(ctx interface{}, queryName interface{}) *MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call {
	return &MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call{Call: _e.mock.On("RecordStorageInsertErrorsCounter", ctx, queryName)}
}

func (_c *MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call) Run(run func(ctx context.Context, queryName string)) *MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call) Return() *MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call) RunAndReturn(run func(context.Context, string)) *MockIndexerMetricLabeler_RecordStorageInsertErrorsCounter_Call {
	_c.Run(run)
	return _c
}

// RecordStorageQueryDuration provides a mock function with given fields: ctx, duration, queryName, errored
func (_m *MockIndexerMetricLabeler) RecordStorageQueryDuration(ctx context.Context, duration time.Duration, queryName string, errored bool) {
	_m.Called(ctx, duration, queryName, errored)
}

// MockIndexerMetricLabeler_RecordStorageQueryDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStorageQueryDuration'
type MockIndexerMetricLabeler_RecordStorageQueryDuration_Call struct {
	*mock.Call
}

// RecordStorageQueryDuration is a helper method to define mock.On call
//   - ctx context.Context
//   - duration time.Duration
//   - queryName string
//   - errored bool
func (_e *MockIndexerMetricLabeler_Expecter) RecordStorageQueryDuration(ctx interface{}, duration interface{}, queryName interface{}, errored interface{}) *MockIndexerMetricLabeler_RecordStorageQueryDuration_Call {
	return &MockIndexerMetricLabeler_RecordStorageQueryDuration_Call{Call: _e.mock.On("RecordStorageQueryDuration", ctx, duration, queryName, errored)}
}

func (_c *MockIndexerMetricLabeler_RecordStorageQueryDuration_Call) Run(run func(ctx context.Context, duration time.Duration, queryName string, errored bool)) *MockIndexerMetricLabeler_RecordStorageQueryDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordStorageQueryDuration_Call) Return() *MockIndexerMetricLabeler_RecordStorageQueryDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordStorageQueryDuration_Call) RunAndReturn(run func(context.Context, time.Duration, string, bool)) *MockIndexerMetricLabeler_RecordStorageQueryDuration_Call {
	_c.Run(run)
	return _c
}

// RecordStorageWriteDuration provides a mock function with given fields: ctx, duration
func (_m *MockIndexerMetricLabeler) RecordStorageWriteDuration(ctx context.Context, duration time.Duration) {
	_m.Called(ctx, duration)
}

// MockIndexerMetricLabeler_RecordStorageWriteDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStorageWriteDuration'
type MockIndexerMetricLabeler_RecordStorageWriteDuration_Call struct {
	*mock.Call
}

// RecordStorageWriteDuration is a helper method to define mock.On call
//   - ctx context.Context
//   - duration time.Duration
func (_e *MockIndexerMetricLabeler_Expecter) RecordStorageWriteDuration(ctx interface{}, duration interface{}) *MockIndexerMetricLabeler_RecordStorageWriteDuration_Call {
	return &MockIndexerMetricLabeler_RecordStorageWriteDuration_Call{Call: _e.mock.On("RecordStorageWriteDuration", ctx, duration)}
}

func (_c *MockIndexerMetricLabeler_RecordStorageWriteDuration_Call) Run(run func(ctx context.Context, duration time.Duration)) *MockIndexerMetricLabeler_RecordStorageWriteDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordStorageWriteDuration_Call) Return() *MockIndexerMetricLabeler_RecordStorageWriteDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordStorageWriteDuration_Call) RunAndReturn(run func(context.Context, time.Duration)) *MockIndexerMetricLabeler_RecordStorageWriteDuration_Call {
	_c.Run(run)
	return _c
}

// RecordTimeToIndex provides a mock function with given fields: ctx, latency, discoveryType
func (_m *MockIndexerMetricLabeler) RecordTimeToIndex(ctx context.Context, latency time.Duration, discoveryType string) {
	_m.Called(ctx, latency, discoveryType)
}

// MockIndexerMetricLabeler_RecordTimeToIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordTimeToIndex'
type MockIndexerMetricLabeler_RecordTimeToIndex_Call struct {
	*mock.Call
}

// RecordTimeToIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - latency time.Duration
//   - discoveryType string
func (_e *MockIndexerMetricLabeler_Expecter) RecordTimeToIndex(ctx interface{}, latency interface{}, discoveryType interface{}) *MockIndexerMetricLabeler_RecordTimeToIndex_Call {
	return &MockIndexerMetricLabeler_RecordTimeToIndex_Call{Call: _e.mock.On("RecordTimeToIndex", ctx, latency, discoveryType)}
}

func (_c *MockIndexerMetricLabeler_RecordTimeToIndex_Call) Run(run func(ctx context.Context, latency time.Duration, discoveryType string)) *MockIndexerMetricLabeler_RecordTimeToIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration), args[2].(string))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordTimeToIndex_Call) Return() *MockIndexerMetricLabeler_RecordTimeToIndex_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordTimeToIndex_Call) RunAndReturn(run func(context.Context, time.Duration, string)) *MockIndexerMetricLabeler_RecordTimeToIndex_Call {
	_c.Run(run)
	return _c
}

// RecordVerificationRecordChannelSizeGauge provides a mock function with given fields: ctx, size
func (_m *MockIndexerMetricLabeler) RecordVerificationRecordChannelSizeGauge(ctx context.Context, size int64) {
	_m.Called(ctx, size)
}

// MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordVerificationRecordChannelSizeGauge'
type MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call struct {
	*mock.Call
}

// RecordVerificationRecordChannelSizeGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - size int64
func (_e *MockIndexerMetricLabeler_Expecter) RecordVerificationRecordChannelSizeGauge(ctx interface{}, size interface{}) *MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call {
	return &MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call{Call: _e.mock.On("RecordVerificationRecordChannelSizeGauge", ctx, size)}
}

func (_c *MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call) Run(run func(ctx context.Context, size int64)) *MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call) Return() *MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call) RunAndReturn(run func(context.Context, int64)) *MockIndexerMetricLabeler_RecordVerificationRecordChannelSizeGauge_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function with given fields: keyValues
func (_m *MockIndexerMetricLabeler) With(keyValues ...string) common.IndexerMetricLabeler {
	_va := make([]interface{}, len(keyValues))
	for _i := range keyValues {
		_va[_i] = keyValues[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 common.IndexerMetricLabeler
	if rf, ok := ret.Get(0).(func(...string) common.IndexerMetricLabeler); ok {
		r0 = rf(keyValues...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.IndexerMetricLabeler)
		}
	}

	return r0
}

// MockIndexerMetricLabeler_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type MockIndexerMetricLabeler_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - keyValues ...string
func (_e *MockIndexerMetricLabeler_Expecter) With(keyValues ...interface{}) *MockIndexerMetricLabeler_With_Call {
	return &MockIndexerMetricLabeler_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, keyValues...)...)}
}

func (_c *MockIndexerMetricLabeler_With_Call) Run(run func(keyValues ...string)) *MockIndexerMetricLabeler_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIndexerMetricLabeler_With_Call) Return(_a0 common.IndexerMetricLabeler) *MockIndexerMetricLabeler_With_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexerMetricLabeler_With_Call) RunAndReturn(run func(...string) common.IndexerMetricLabeler) *MockIndexerMetricLabeler_With_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIndexerMetricLabeler creates a new instance of MockIndexerMetricLabeler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexerMetricLabeler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexerMetricLabeler {
	mock := &MockIndexerMetricLabeler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
