// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	v2 "github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockUpdateServiceClient is an autogenerated mock type for the UpdateServiceClient type
type MockUpdateServiceClient struct {
	mock.Mock
}

type MockUpdateServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateServiceClient) EXPECT() *MockUpdateServiceClient_Expecter {
	return &MockUpdateServiceClient_Expecter{mock: &_m.Mock}
}

// GetTransactionById provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateServiceClient) GetTransactionById(ctx context.Context, in *v2.GetTransactionByIdRequest, opts ...grpc.CallOption) (*v2.GetTransactionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionById")
	}

	var r0 *v2.GetTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetTransactionByIdRequest, ...grpc.CallOption) (*v2.GetTransactionResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetTransactionByIdRequest, ...grpc.CallOption) *v2.GetTransactionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetTransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.GetTransactionByIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateServiceClient_GetTransactionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionById'
type MockUpdateServiceClient_GetTransactionById_Call struct {
	*mock.Call
}

// GetTransactionById is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetTransactionByIdRequest
//   - opts ...grpc.CallOption
func (_e *MockUpdateServiceClient_Expecter) GetTransactionById(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateServiceClient_GetTransactionById_Call {
	return &MockUpdateServiceClient_GetTransactionById_Call{Call: _e.mock.On("GetTransactionById",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateServiceClient_GetTransactionById_Call) Run(run func(ctx context.Context, in *v2.GetTransactionByIdRequest, opts ...grpc.CallOption)) *MockUpdateServiceClient_GetTransactionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.GetTransactionByIdRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateServiceClient_GetTransactionById_Call) Return(_a0 *v2.GetTransactionResponse, _a1 error) *MockUpdateServiceClient_GetTransactionById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateServiceClient_GetTransactionById_Call) RunAndReturn(run func(context.Context, *v2.GetTransactionByIdRequest, ...grpc.CallOption) (*v2.GetTransactionResponse, error)) *MockUpdateServiceClient_GetTransactionById_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionByOffset provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateServiceClient) GetTransactionByOffset(ctx context.Context, in *v2.GetTransactionByOffsetRequest, opts ...grpc.CallOption) (*v2.GetTransactionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByOffset")
	}

	var r0 *v2.GetTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetTransactionByOffsetRequest, ...grpc.CallOption) (*v2.GetTransactionResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetTransactionByOffsetRequest, ...grpc.CallOption) *v2.GetTransactionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetTransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.GetTransactionByOffsetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateServiceClient_GetTransactionByOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByOffset'
type MockUpdateServiceClient_GetTransactionByOffset_Call struct {
	*mock.Call
}

// GetTransactionByOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetTransactionByOffsetRequest
//   - opts ...grpc.CallOption
func (_e *MockUpdateServiceClient_Expecter) GetTransactionByOffset(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateServiceClient_GetTransactionByOffset_Call {
	return &MockUpdateServiceClient_GetTransactionByOffset_Call{Call: _e.mock.On("GetTransactionByOffset",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateServiceClient_GetTransactionByOffset_Call) Run(run func(ctx context.Context, in *v2.GetTransactionByOffsetRequest, opts ...grpc.CallOption)) *MockUpdateServiceClient_GetTransactionByOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.GetTransactionByOffsetRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateServiceClient_GetTransactionByOffset_Call) Return(_a0 *v2.GetTransactionResponse, _a1 error) *MockUpdateServiceClient_GetTransactionByOffset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateServiceClient_GetTransactionByOffset_Call) RunAndReturn(run func(context.Context, *v2.GetTransactionByOffsetRequest, ...grpc.CallOption) (*v2.GetTransactionResponse, error)) *MockUpdateServiceClient_GetTransactionByOffset_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionTreeById provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateServiceClient) GetTransactionTreeById(ctx context.Context, in *v2.GetTransactionByIdRequest, opts ...grpc.CallOption) (*v2.GetTransactionTreeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionTreeById")
	}

	var r0 *v2.GetTransactionTreeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetTransactionByIdRequest, ...grpc.CallOption) (*v2.GetTransactionTreeResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetTransactionByIdRequest, ...grpc.CallOption) *v2.GetTransactionTreeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetTransactionTreeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.GetTransactionByIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateServiceClient_GetTransactionTreeById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionTreeById'
type MockUpdateServiceClient_GetTransactionTreeById_Call struct {
	*mock.Call
}

// GetTransactionTreeById is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetTransactionByIdRequest
//   - opts ...grpc.CallOption
func (_e *MockUpdateServiceClient_Expecter) GetTransactionTreeById(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateServiceClient_GetTransactionTreeById_Call {
	return &MockUpdateServiceClient_GetTransactionTreeById_Call{Call: _e.mock.On("GetTransactionTreeById",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateServiceClient_GetTransactionTreeById_Call) Run(run func(ctx context.Context, in *v2.GetTransactionByIdRequest, opts ...grpc.CallOption)) *MockUpdateServiceClient_GetTransactionTreeById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.GetTransactionByIdRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateServiceClient_GetTransactionTreeById_Call) Return(_a0 *v2.GetTransactionTreeResponse, _a1 error) *MockUpdateServiceClient_GetTransactionTreeById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateServiceClient_GetTransactionTreeById_Call) RunAndReturn(run func(context.Context, *v2.GetTransactionByIdRequest, ...grpc.CallOption) (*v2.GetTransactionTreeResponse, error)) *MockUpdateServiceClient_GetTransactionTreeById_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionTreeByOffset provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateServiceClient) GetTransactionTreeByOffset(ctx context.Context, in *v2.GetTransactionByOffsetRequest, opts ...grpc.CallOption) (*v2.GetTransactionTreeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionTreeByOffset")
	}

	var r0 *v2.GetTransactionTreeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetTransactionByOffsetRequest, ...grpc.CallOption) (*v2.GetTransactionTreeResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetTransactionByOffsetRequest, ...grpc.CallOption) *v2.GetTransactionTreeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetTransactionTreeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.GetTransactionByOffsetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateServiceClient_GetTransactionTreeByOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionTreeByOffset'
type MockUpdateServiceClient_GetTransactionTreeByOffset_Call struct {
	*mock.Call
}

// GetTransactionTreeByOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetTransactionByOffsetRequest
//   - opts ...grpc.CallOption
func (_e *MockUpdateServiceClient_Expecter) GetTransactionTreeByOffset(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateServiceClient_GetTransactionTreeByOffset_Call {
	return &MockUpdateServiceClient_GetTransactionTreeByOffset_Call{Call: _e.mock.On("GetTransactionTreeByOffset",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateServiceClient_GetTransactionTreeByOffset_Call) Run(run func(ctx context.Context, in *v2.GetTransactionByOffsetRequest, opts ...grpc.CallOption)) *MockUpdateServiceClient_GetTransactionTreeByOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.GetTransactionByOffsetRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateServiceClient_GetTransactionTreeByOffset_Call) Return(_a0 *v2.GetTransactionTreeResponse, _a1 error) *MockUpdateServiceClient_GetTransactionTreeByOffset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateServiceClient_GetTransactionTreeByOffset_Call) RunAndReturn(run func(context.Context, *v2.GetTransactionByOffsetRequest, ...grpc.CallOption) (*v2.GetTransactionTreeResponse, error)) *MockUpdateServiceClient_GetTransactionTreeByOffset_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdateById provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateServiceClient) GetUpdateById(ctx context.Context, in *v2.GetUpdateByIdRequest, opts ...grpc.CallOption) (*v2.GetUpdateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUpdateById")
	}

	var r0 *v2.GetUpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetUpdateByIdRequest, ...grpc.CallOption) (*v2.GetUpdateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetUpdateByIdRequest, ...grpc.CallOption) *v2.GetUpdateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetUpdateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.GetUpdateByIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateServiceClient_GetUpdateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdateById'
type MockUpdateServiceClient_GetUpdateById_Call struct {
	*mock.Call
}

// GetUpdateById is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetUpdateByIdRequest
//   - opts ...grpc.CallOption
func (_e *MockUpdateServiceClient_Expecter) GetUpdateById(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateServiceClient_GetUpdateById_Call {
	return &MockUpdateServiceClient_GetUpdateById_Call{Call: _e.mock.On("GetUpdateById",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateServiceClient_GetUpdateById_Call) Run(run func(ctx context.Context, in *v2.GetUpdateByIdRequest, opts ...grpc.CallOption)) *MockUpdateServiceClient_GetUpdateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.GetUpdateByIdRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateServiceClient_GetUpdateById_Call) Return(_a0 *v2.GetUpdateResponse, _a1 error) *MockUpdateServiceClient_GetUpdateById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateServiceClient_GetUpdateById_Call) RunAndReturn(run func(context.Context, *v2.GetUpdateByIdRequest, ...grpc.CallOption) (*v2.GetUpdateResponse, error)) *MockUpdateServiceClient_GetUpdateById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdateByOffset provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateServiceClient) GetUpdateByOffset(ctx context.Context, in *v2.GetUpdateByOffsetRequest, opts ...grpc.CallOption) (*v2.GetUpdateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUpdateByOffset")
	}

	var r0 *v2.GetUpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetUpdateByOffsetRequest, ...grpc.CallOption) (*v2.GetUpdateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetUpdateByOffsetRequest, ...grpc.CallOption) *v2.GetUpdateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetUpdateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.GetUpdateByOffsetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateServiceClient_GetUpdateByOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdateByOffset'
type MockUpdateServiceClient_GetUpdateByOffset_Call struct {
	*mock.Call
}

// GetUpdateByOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetUpdateByOffsetRequest
//   - opts ...grpc.CallOption
func (_e *MockUpdateServiceClient_Expecter) GetUpdateByOffset(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateServiceClient_GetUpdateByOffset_Call {
	return &MockUpdateServiceClient_GetUpdateByOffset_Call{Call: _e.mock.On("GetUpdateByOffset",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateServiceClient_GetUpdateByOffset_Call) Run(run func(ctx context.Context, in *v2.GetUpdateByOffsetRequest, opts ...grpc.CallOption)) *MockUpdateServiceClient_GetUpdateByOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.GetUpdateByOffsetRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateServiceClient_GetUpdateByOffset_Call) Return(_a0 *v2.GetUpdateResponse, _a1 error) *MockUpdateServiceClient_GetUpdateByOffset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateServiceClient_GetUpdateByOffset_Call) RunAndReturn(run func(context.Context, *v2.GetUpdateByOffsetRequest, ...grpc.CallOption) (*v2.GetUpdateResponse, error)) *MockUpdateServiceClient_GetUpdateByOffset_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdateTrees provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateServiceClient) GetUpdateTrees(ctx context.Context, in *v2.GetUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetUpdateTreesResponse], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUpdateTrees")
	}

	var r0 grpc.ServerStreamingClient[v2.GetUpdateTreesResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetUpdatesRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetUpdateTreesResponse], error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetUpdatesRequest, ...grpc.CallOption) grpc.ServerStreamingClient[v2.GetUpdateTreesResponse]); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[v2.GetUpdateTreesResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.GetUpdatesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateServiceClient_GetUpdateTrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdateTrees'
type MockUpdateServiceClient_GetUpdateTrees_Call struct {
	*mock.Call
}

// GetUpdateTrees is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetUpdatesRequest
//   - opts ...grpc.CallOption
func (_e *MockUpdateServiceClient_Expecter) GetUpdateTrees(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateServiceClient_GetUpdateTrees_Call {
	return &MockUpdateServiceClient_GetUpdateTrees_Call{Call: _e.mock.On("GetUpdateTrees",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateServiceClient_GetUpdateTrees_Call) Run(run func(ctx context.Context, in *v2.GetUpdatesRequest, opts ...grpc.CallOption)) *MockUpdateServiceClient_GetUpdateTrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.GetUpdatesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateServiceClient_GetUpdateTrees_Call) Return(_a0 grpc.ServerStreamingClient[v2.GetUpdateTreesResponse], _a1 error) *MockUpdateServiceClient_GetUpdateTrees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateServiceClient_GetUpdateTrees_Call) RunAndReturn(run func(context.Context, *v2.GetUpdatesRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetUpdateTreesResponse], error)) *MockUpdateServiceClient_GetUpdateTrees_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdates provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateServiceClient) GetUpdates(ctx context.Context, in *v2.GetUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetUpdatesResponse], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUpdates")
	}

	var r0 grpc.ServerStreamingClient[v2.GetUpdatesResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetUpdatesRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetUpdatesResponse], error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.GetUpdatesRequest, ...grpc.CallOption) grpc.ServerStreamingClient[v2.GetUpdatesResponse]); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[v2.GetUpdatesResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.GetUpdatesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateServiceClient_GetUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdates'
type MockUpdateServiceClient_GetUpdates_Call struct {
	*mock.Call
}

// GetUpdates is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetUpdatesRequest
//   - opts ...grpc.CallOption
func (_e *MockUpdateServiceClient_Expecter) GetUpdates(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateServiceClient_GetUpdates_Call {
	return &MockUpdateServiceClient_GetUpdates_Call{Call: _e.mock.On("GetUpdates",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateServiceClient_GetUpdates_Call) Run(run func(ctx context.Context, in *v2.GetUpdatesRequest, opts ...grpc.CallOption)) *MockUpdateServiceClient_GetUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.GetUpdatesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateServiceClient_GetUpdates_Call) Return(_a0 grpc.ServerStreamingClient[v2.GetUpdatesResponse], _a1 error) *MockUpdateServiceClient_GetUpdates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateServiceClient_GetUpdates_Call) RunAndReturn(run func(context.Context, *v2.GetUpdatesRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetUpdatesResponse], error)) *MockUpdateServiceClient_GetUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateServiceClient creates a new instance of MockUpdateServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateServiceClient {
	mock := &MockUpdateServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
