// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	chainaccess "github.com/smartcontractkit/chainlink-ccv/pkg/chainaccess"
	mock "github.com/stretchr/testify/mock"
)

// MockAccessor is an autogenerated mock type for the Accessor type
type MockAccessor struct {
	mock.Mock
}

type MockAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessor) EXPECT() *MockAccessor_Expecter {
	return &MockAccessor_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockAccessor) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccessor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAccessor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockAccessor_Expecter) Close() *MockAccessor_Close_Call {
	return &MockAccessor_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockAccessor_Close_Call) Run(run func()) *MockAccessor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccessor_Close_Call) Return(_a0 error) *MockAccessor_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccessor_Close_Call) RunAndReturn(run func() error) *MockAccessor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ContractTransmitter provides a mock function with no fields
func (_m *MockAccessor) ContractTransmitter() (chainaccess.ContractTransmitter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContractTransmitter")
	}

	var r0 chainaccess.ContractTransmitter
	var r1 error
	if rf, ok := ret.Get(0).(func() (chainaccess.ContractTransmitter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() chainaccess.ContractTransmitter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chainaccess.ContractTransmitter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessor_ContractTransmitter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContractTransmitter'
type MockAccessor_ContractTransmitter_Call struct {
	*mock.Call
}

// ContractTransmitter is a helper method to define mock.On call
func (_e *MockAccessor_Expecter) ContractTransmitter() *MockAccessor_ContractTransmitter_Call {
	return &MockAccessor_ContractTransmitter_Call{Call: _e.mock.On("ContractTransmitter")}
}

func (_c *MockAccessor_ContractTransmitter_Call) Run(run func()) *MockAccessor_ContractTransmitter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccessor_ContractTransmitter_Call) Return(_a0 chainaccess.ContractTransmitter, _a1 error) *MockAccessor_ContractTransmitter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessor_ContractTransmitter_Call) RunAndReturn(run func() (chainaccess.ContractTransmitter, error)) *MockAccessor_ContractTransmitter_Call {
	_c.Call.Return(run)
	return _c
}

// DestinationReader provides a mock function with no fields
func (_m *MockAccessor) DestinationReader() (chainaccess.DestinationReader, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DestinationReader")
	}

	var r0 chainaccess.DestinationReader
	var r1 error
	if rf, ok := ret.Get(0).(func() (chainaccess.DestinationReader, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() chainaccess.DestinationReader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chainaccess.DestinationReader)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessor_DestinationReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestinationReader'
type MockAccessor_DestinationReader_Call struct {
	*mock.Call
}

// DestinationReader is a helper method to define mock.On call
func (_e *MockAccessor_Expecter) DestinationReader() *MockAccessor_DestinationReader_Call {
	return &MockAccessor_DestinationReader_Call{Call: _e.mock.On("DestinationReader")}
}

func (_c *MockAccessor_DestinationReader_Call) Run(run func()) *MockAccessor_DestinationReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccessor_DestinationReader_Call) Return(_a0 chainaccess.DestinationReader, _a1 error) *MockAccessor_DestinationReader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessor_DestinationReader_Call) RunAndReturn(run func() (chainaccess.DestinationReader, error)) *MockAccessor_DestinationReader_Call {
	_c.Call.Return(run)
	return _c
}

// SourceReader provides a mock function with no fields
func (_m *MockAccessor) SourceReader() (chainaccess.SourceReader, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SourceReader")
	}

	var r0 chainaccess.SourceReader
	var r1 error
	if rf, ok := ret.Get(0).(func() (chainaccess.SourceReader, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() chainaccess.SourceReader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chainaccess.SourceReader)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessor_SourceReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceReader'
type MockAccessor_SourceReader_Call struct {
	*mock.Call
}

// SourceReader is a helper method to define mock.On call
func (_e *MockAccessor_Expecter) SourceReader() *MockAccessor_SourceReader_Call {
	return &MockAccessor_SourceReader_Call{Call: _e.mock.On("SourceReader")}
}

func (_c *MockAccessor_SourceReader_Call) Run(run func()) *MockAccessor_SourceReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccessor_SourceReader_Call) Return(_a0 chainaccess.SourceReader, _a1 error) *MockAccessor_SourceReader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessor_SourceReader_Call) RunAndReturn(run func() (chainaccess.SourceReader, error)) *MockAccessor_SourceReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessor creates a new instance of MockAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessor {
	mock := &MockAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
