// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/smartcontractkit/chainlink-ccv/aggregator/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MockAggregationTriggerer is an autogenerated mock type for the AggregationTriggerer type
type MockAggregationTriggerer struct {
	mock.Mock
}

type MockAggregationTriggerer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggregationTriggerer) EXPECT() *MockAggregationTriggerer_Expecter {
	return &MockAggregationTriggerer_Expecter{mock: &_m.Mock}
}

// CheckAggregation provides a mock function with given fields: ctx, messageID, aggregationKey, channelKey
func (_m *MockAggregationTriggerer) CheckAggregation(ctx context.Context, messageID []byte, aggregationKey string, channelKey model.ChannelKey) error {
	ret := _m.Called(ctx, messageID, aggregationKey, channelKey)

	if len(ret) == 0 {
		panic("no return value specified for CheckAggregation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, model.ChannelKey) error); ok {
		r0 = rf(ctx, messageID, aggregationKey, channelKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAggregationTriggerer_CheckAggregation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAggregation'
type MockAggregationTriggerer_CheckAggregation_Call struct {
	*mock.Call
}

// CheckAggregation is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID []byte
//   - aggregationKey string
//   - channelKey model.ChannelKey
func (_e *MockAggregationTriggerer_Expecter) CheckAggregation(ctx interface{}, messageID interface{}, aggregationKey interface{}, channelKey interface{}) *MockAggregationTriggerer_CheckAggregation_Call {
	return &MockAggregationTriggerer_CheckAggregation_Call{Call: _e.mock.On("CheckAggregation", ctx, messageID, aggregationKey, channelKey)}
}

func (_c *MockAggregationTriggerer_CheckAggregation_Call) Run(run func(ctx context.Context, messageID []byte, aggregationKey string, channelKey model.ChannelKey)) *MockAggregationTriggerer_CheckAggregation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string), args[3].(model.ChannelKey))
	})
	return _c
}

func (_c *MockAggregationTriggerer_CheckAggregation_Call) Return(_a0 error) *MockAggregationTriggerer_CheckAggregation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregationTriggerer_CheckAggregation_Call) RunAndReturn(run func(context.Context, []byte, string, model.ChannelKey) error) *MockAggregationTriggerer_CheckAggregation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAggregationTriggerer creates a new instance of MockAggregationTriggerer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregationTriggerer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregationTriggerer {
	mock := &MockAggregationTriggerer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
