// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	v1 "github.com/smartcontractkit/chainlink-protos/chainlink-ccv/verifier/v1"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockVerifierClient is an autogenerated mock type for the VerifierClient type
type MockVerifierClient struct {
	mock.Mock
}

type MockVerifierClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifierClient) EXPECT() *MockVerifierClient_Expecter {
	return &MockVerifierClient_Expecter{mock: &_m.Mock}
}

// GetVerifierResultsForMessage provides a mock function with given fields: ctx, in, opts
func (_m *MockVerifierClient) GetVerifierResultsForMessage(ctx context.Context, in *v1.GetVerifierResultsForMessageRequest, opts ...grpc.CallOption) (*v1.GetVerifierResultsForMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetVerifierResultsForMessage")
	}

	var r0 *v1.GetVerifierResultsForMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetVerifierResultsForMessageRequest, ...grpc.CallOption) (*v1.GetVerifierResultsForMessageResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetVerifierResultsForMessageRequest, ...grpc.CallOption) *v1.GetVerifierResultsForMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetVerifierResultsForMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.GetVerifierResultsForMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerifierClient_GetVerifierResultsForMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVerifierResultsForMessage'
type MockVerifierClient_GetVerifierResultsForMessage_Call struct {
	*mock.Call
}

// GetVerifierResultsForMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.GetVerifierResultsForMessageRequest
//   - opts ...grpc.CallOption
func (_e *MockVerifierClient_Expecter) GetVerifierResultsForMessage(ctx interface{}, in interface{}, opts ...interface{}) *MockVerifierClient_GetVerifierResultsForMessage_Call {
	return &MockVerifierClient_GetVerifierResultsForMessage_Call{Call: _e.mock.On("GetVerifierResultsForMessage",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockVerifierClient_GetVerifierResultsForMessage_Call) Run(run func(ctx context.Context, in *v1.GetVerifierResultsForMessageRequest, opts ...grpc.CallOption)) *MockVerifierClient_GetVerifierResultsForMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1.GetVerifierResultsForMessageRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockVerifierClient_GetVerifierResultsForMessage_Call) Return(_a0 *v1.GetVerifierResultsForMessageResponse, _a1 error) *MockVerifierClient_GetVerifierResultsForMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerifierClient_GetVerifierResultsForMessage_Call) RunAndReturn(run func(context.Context, *v1.GetVerifierResultsForMessageRequest, ...grpc.CallOption) (*v1.GetVerifierResultsForMessageResponse, error)) *MockVerifierClient_GetVerifierResultsForMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifierClient creates a new instance of MockVerifierClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifierClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifierClient {
	mock := &MockVerifierClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
