set fallback

import '../tools/lib/utils.justfile'

# Default: show available recipes
default:
    just --list

build-rc:
    docker build -f Dockerfile -t pricereporter:rc ..

build-dev:
    docker build -f Dockerfile.dev -t pricereporter:dev ..

publish-rc registry version:
    docker tag pricereporter:rc {{registry}}/chainlink-ccv-pricereporter:{{version}}-rc
    docker push {{registry}}/chainlink-ccv-pricereporter:{{version}}-rc

run config="config.toml": build-rc
    docker run --rm -v {{justfile_directory()}}/{{config}}:/config.toml pricereporter:rc --config /config.toml

run-dev: build-dev
    docker run --rm -v {{justfile_directory()}}/..:/app pricereporter:dev

clean:
    docker rmi pricereporter:latest

clean-dev:
    docker rmi pricereporter:dev
