// Code generated by github.com/smartcontractkit/chainlink-ccv/tools/configdoc, DO NOT EDIT.

package admin

import "github.com/smartcontractkit/chainlink-common/x/config/commentparsing"

func (AccessConfig) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"ActorHeader": {Comment: "ActorHeader names the HTTP header carrying an authenticated identity from a\nfronting proxy (shared hosting). Empty means self-hosted loopback: actor \"local\".\nNon-loopback serving requires this header or [admin_ui] basic auth from the\nverifier secrets file (validated at startup, when the secrets are loaded)."},
	}
}

func (Config) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"Access":            {Comment: "Access configures how the console identifies who is acting."},
		"AggregatorAddress": {Comment: "AggregatorAddress (optional, host:port) overrides the aggregator used for\nattestation freshness checks via the unauthenticated GetVerifierResultsForMessage.\nEmpty uses the verifier's own first configured aggregator."},
		"ListenAddress":     {Comment: "ListenAddress is the bind address; loopback by default."},
		"TraceURL":          {Comment: "TraceURL (optional) is a base URL to the operator's trace viewer — typically an\ninternal Grafana/Tempo or Jaeger — linked from the message detail page when set."},
	}
}
