// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	"github.com/smartcontractkit/chainlink-ccv/protocol"
)

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// Message defines model for Message.
type Message struct {
	CcipReceiveGasLimit  int32         `json:"ccip_receive_gas_limit"`
	CcvAndExecutorHash   string        `json:"ccv_and_executor_hash"`
	Data                 string        `json:"data"`
	DataLength           int32         `json:"data_length"`
	DestBlob             string        `json:"dest_blob"`
	DestBlobLength       int32         `json:"dest_blob_length"`
	DestChainSelector    int64         `json:"dest_chain_selector"`
	ExecutionGasLimit    int32         `json:"execution_gas_limit"`
	Finality             int32         `json:"finality"`
	OffRampAddress       string        `json:"off_ramp_address"`
	OffRampAddressLength int32         `json:"off_ramp_address_length"`
	OnRampAddress        string        `json:"on_ramp_address"`
	OnRampAddressLength  int32         `json:"on_ramp_address_length"`
	Receiver             string        `json:"receiver"`
	ReceiverLength       int32         `json:"receiver_length"`
	Sender               string        `json:"sender"`
	SenderLength         int32         `json:"sender_length"`
	SequenceNumber       int64         `json:"sequence_number"`
	SourceChainSelector  int64         `json:"source_chain_selector"`
	TokenTransfer        TokenTransfer `json:"token_transfer"`
	TokenTransferLength  int32         `json:"token_transfer_length"`
	Version              int32         `json:"version"`
}

// MessageMetadata defines model for MessageMetadata.
type MessageMetadata struct {
	IngestionTimestamp time.Time `json:"ingestionTimestamp"`
	Status             int64     `json:"status"`
}

// MessageWithMetadata defines model for MessageWithMetadata.
type MessageWithMetadata struct {
	Message  Message         `json:"message"`
	Metadata MessageMetadata `json:"metadata"`
}

// TokenTransfer defines model for TokenTransfer.
type TokenTransfer struct {
	Amount                   *string `json:"amount"`
	DestTokenAddress         string  `json:"dest_token_address"`
	DestTokenAddressLength   int32   `json:"dest_token_address_length"`
	ExtraData                string  `json:"extra_data"`
	ExtraDataLength          int32   `json:"extra_data_length"`
	SourcePoolAddress        string  `json:"source_pool_address"`
	SourcePoolAddressLength  int32   `json:"source_pool_address_length"`
	SourceTokenAddress       string  `json:"source_token_address"`
	SourceTokenAddressLength int32   `json:"source_token_address_length"`
	TokenReceiver            string  `json:"token_receiver"`
	TokenReceiverLength      int32   `json:"token_receiver_length"`
	Version                  int32   `json:"version"`
}

// VerifierResult defines model for VerifierResult.
type VerifierResult struct {
	CcvData                string    `json:"ccv_data"`
	Message                Message   `json:"message"`
	MessageCcvAddresses    *[]string `json:"message_ccv_addresses"`
	MessageExecutorAddress string    `json:"message_executor_address"`
	MessageId              string    `json:"message_id"`
	Timestamp              time.Time `json:"timestamp"`
	VerifierDestAddress    string    `json:"verifier_dest_address"`
	VerifierSourceAddress  string    `json:"verifier_source_address"`
}

// VerifierResultMetadata defines model for VerifierResultMetadata.
type VerifierResultMetadata struct {
	AttestationTimestamp time.Time `json:"attestationTimestamp"`
	IngestionTimestamp   time.Time `json:"ingestionTimestamp"`
	VerifierName         string    `json:"verifierName"`
}

// VerifierResultWithMetadata defines model for VerifierResultWithMetadata.
type VerifierResultWithMetadata struct {
	Metadata       VerifierResultMetadata `json:"metadata"`
	VerifierResult VerifierResult         `json:"verifierResult"`
}

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	SourceChainSelectors *[]protocol.ChainSelector `form:"sourceChainSelectors,omitempty" json:"sourceChainSelectors,omitempty"`
	DestChainSelectors   *[]protocol.ChainSelector `form:"destChainSelectors,omitempty" json:"destChainSelectors,omitempty"`
	Start                *int64                    `form:"start,omitempty" json:"start,omitempty"`
	End                  *int64                    `form:"end,omitempty" json:"end,omitempty"`
	Limit                *uint64                   `form:"limit,omitempty" json:"limit,omitempty"`
	Offset               *uint64                   `form:"offset,omitempty" json:"offset,omitempty"`
}

// VerifierResultParams defines parameters for VerifierResult.
type VerifierResultParams struct {
	SourceChainSelectors *[]protocol.ChainSelector `form:"sourceChainSelectors,omitempty" json:"sourceChainSelectors,omitempty"`
	DestChainSelectors   *[]protocol.ChainSelector `form:"destChainSelectors,omitempty" json:"destChainSelectors,omitempty"`
	Start                *int64                    `form:"start,omitempty" json:"start,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// MessageById request
	MessageById(ctx context.Context, messageID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMessages request
	GetMessages(ctx context.Context, params *GetMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VerifierResult request
	VerifierResult(ctx context.Context, params *VerifierResultParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) MessageById(ctx context.Context, messageID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMessageByIdRequest(c.Server, messageID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMessages(ctx context.Context, params *GetMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMessagesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VerifierResult(ctx context.Context, params *VerifierResultParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVerifierResultRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewMessageByIdRequest generates requests for MessageById
func NewMessageByIdRequest(server string, messageID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "messageID", runtime.ParamLocationPath, messageID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/messageid/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMessagesRequest generates requests for GetMessages
func NewGetMessagesRequest(server string, params *GetMessagesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/messages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.SourceChainSelectors != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "sourceChainSelectors", runtime.ParamLocationQuery, *params.SourceChainSelectors); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DestChainSelectors != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "destChainSelectors", runtime.ParamLocationQuery, *params.DestChainSelectors); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Start != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "start", runtime.ParamLocationQuery, *params.Start); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.End != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "end", runtime.ParamLocationQuery, *params.End); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewVerifierResultRequest generates requests for VerifierResult
func NewVerifierResultRequest(server string, params *VerifierResultParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/verifierresult")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.SourceChainSelectors != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "sourceChainSelectors", runtime.ParamLocationQuery, *params.SourceChainSelectors); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DestChainSelectors != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "destChainSelectors", runtime.ParamLocationQuery, *params.DestChainSelectors); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Start != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "start", runtime.ParamLocationQuery, *params.Start); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// MessageByIdWithResponse request
	MessageByIdWithResponse(ctx context.Context, messageID string, reqEditors ...RequestEditorFn) (*MessageByIdResponse, error)

	// GetMessagesWithResponse request
	GetMessagesWithResponse(ctx context.Context, params *GetMessagesParams, reqEditors ...RequestEditorFn) (*GetMessagesResponse, error)

	// VerifierResultWithResponse request
	VerifierResultWithResponse(ctx context.Context, params *VerifierResultParams, reqEditors ...RequestEditorFn) (*VerifierResultResponse, error)
}

type MessageByIdResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r MessageByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MessageByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMessagesResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VerifierResultResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r VerifierResultResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VerifierResultResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// MessageByIdWithResponse request returning *MessageByIdResponse
func (c *ClientWithResponses) MessageByIdWithResponse(ctx context.Context, messageID string, reqEditors ...RequestEditorFn) (*MessageByIdResponse, error) {
	rsp, err := c.MessageById(ctx, messageID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMessageByIdResponse(rsp)
}

// GetMessagesWithResponse request returning *GetMessagesResponse
func (c *ClientWithResponses) GetMessagesWithResponse(ctx context.Context, params *GetMessagesParams, reqEditors ...RequestEditorFn) (*GetMessagesResponse, error) {
	rsp, err := c.GetMessages(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMessagesResponse(rsp)
}

// VerifierResultWithResponse request returning *VerifierResultResponse
func (c *ClientWithResponses) VerifierResultWithResponse(ctx context.Context, params *VerifierResultParams, reqEditors ...RequestEditorFn) (*VerifierResultResponse, error) {
	rsp, err := c.VerifierResult(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVerifierResultResponse(rsp)
}

// ParseMessageByIdResponse parses an HTTP response from a MessageByIdWithResponse call
func ParseMessageByIdResponse(rsp *http.Response) (*MessageByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MessageByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetMessagesResponse parses an HTTP response from a GetMessagesWithResponse call
func ParseGetMessagesResponse(rsp *http.Response) (*GetMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseVerifierResultResponse parses an HTTP response from a VerifierResultWithResponse call
func ParseVerifierResultResponse(rsp *http.Response) (*VerifierResultResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VerifierResultResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
