with-expecter: true

dir: ./internal/mocks
outpkg: mocks

packages:
  github.com/smartcontractkit/chainlink-ccv/pkg/chainaccess:
    interfaces:
      SourceReader:

  github.com/smartcontractkit/chainlink-ccv/common:
    interfaces:
      CurseChecker:
      CurseCheckerService:
      RMNRemoteReader:
      TimeProvider:

  github.com/smartcontractkit/chainlink-ccv/protocol:
    interfaces:
      ChainStatusManager:
      FinalityViolationChecker:
  github.com/smartcontractkit/chainlink-ccv/protocol/common/chainaccess:
    interfaces:
      HeadTracker:
      SourceReader:
      RMNCurseReader:

  github.com/smartcontractkit/chainlink-ccv/executor:
    interfaces:
      MessageSubscriber:
      Executor:
      ContractTransmitter:
      LeaderElector:
      DestinationReader:
      VerifierResultReader:
      MessageReader:
