with-expecter: true

dir: ./internal/mocks
outpkg: mocks

packages:
  github.com/smartcontractkit/chainlink-ccv/pkg/chainaccess:
    interfaces:
      SourceReader:

  github.com/smartcontractkit/chainlink-ccv/common:
    interfaces:
      CurseChecker:
      CurseCheckerService:
      RMNRemoteReader:
      TimeProvider:

  github.com/smartcontractkit/chainlink-ccv/protocol:
    interfaces:
      ChainStatusManager:
      FinalityViolationChecker:
      VerifierResultsAPI:

  github.com/smartcontractkit/chainlink-ccv/protocol/common/chainaccess:
    interfaces:
      HeadTracker:
      SourceReader:
      RMNCurseReader:

  github.com/smartcontractkit/chainlink-ccv/executor:
    interfaces:
      MessageSubscriber:
      Executor:
      ContractTransmitter:
      LeaderElector:
      DestinationReader:
      VerifierResultReader:
      MessageReader:

  github.com/smartcontractkit/chainlink-ccv/aggregator/pkg/handlers:
    interfaces:
      SignatureValidator:
      AggregationTriggerer:
  github.com/smartcontractkit/chainlink-ccv/aggregator/pkg/common:
    interfaces:
      CommitVerificationStore:
      CommitVerificationAggregatedStore:
      ChainStatusStorageInterface:
      Sink:
      AggregatorMonitoring:
      AggregatorMetricLabeler:
  github.com/smartcontractkit/chainlink-ccv/aggregator/pkg/aggregation:
    interfaces:
      QuorumValidator:

  github.com/smartcontractkit/chainlink-ccv/indexer/pkg/common:
    interfaces:
      IndexerStorage:
  github.com/smartcontractkit/chainlink-ccv/indexer/pkg/client/internal:
    interfaces:
      ClientInterface:
        configs:
          - dir: ./indexer/pkg/client/internal/mocks
