# may be multiple files
profile: cover.out

# Holds coverage thresholds percentages, values should be in range [0-100].
# default coverage threshold for all the packages
threshold:
  file: 50
  package: 50
  total: 50

override:
  # Increase coverage threshold to 100% for `foo` package 
  # (default is 80, as configured above in this example).
  - path: ^verifier.*
    threshold: 70
  - path: ^executor.*
    threshold: 70
  - path: ^aggregator.*
    threshold: 70
  - path: ^indexer.*
    threshold: 70

exclude:
  # Exclude files or packages matching their paths
  paths:
    - .*mock_*
    - \.pb\.go$    # excludes all protobuf generated files

force-annotation-comment: false

# If specified, saves the current test coverage breakdown to this file.
#
# Typically, this breakdown is generated only for main (base) branches and 
# stored as an artifact. Later, this file can be used in feature branches 
# to compare test coverage against the base branch.
breakdown-file-name: 'coverage-breakdown.txt'

diff:
  base-breakdown-file-name: 'coverage-breakdown.txt'