// Code generated by github.com/smartcontractkit/chainlink-ccv/tools/configdoc, DO NOT EDIT.

package monitoring

import "github.com/smartcontractkit/chainlink-common/x/config/commentparsing"

func (BeholderConfig) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"CACertFile":               {Comment: "CACertFile is the path to the CA certificate file for the beholder client."},
		"Enabled":                  {Comment: "Enabled enables the beholder telemetry."},
		"InsecureConnection":       {Comment: "InsecureConnection disables TLS for the beholder client."},
		"LogStreamingEnabled":      {Comment: "LogStreamingEnabled enables log streaming to the collector."},
		"LogStreamingLevel":        {Comment: "LogStreamingLevel specifies the level above which logs are streamed to beholder"},
		"MetricReaderInterval":     {Comment: "MetricReaderInterval is the interval to scrape metrics (in seconds)."},
		"OtelExporterGRPCEndpoint": {Comment: "OtelExporterGRPCEndpoint is the endpoint for the beholder client to export to the collector."},
		"OtelExporterHTTPEndpoint": {Comment: "OtelExporterHTTPEndpoint is the endpoint for the beholder client to export to the collector."},
		"TelemetryAttributes":      {Comment: "TelemetryAttributes are additional labels that assigned during OTel transmission"},
		"TraceBatchTimeout":        {Comment: "TraceBatchTimeout is the timeout for a batch of traces."},
		"TraceSampleRatio":         {Comment: "TraceSampleRatio is the ratio of traces to sample."},
	}
}

func (Config) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"Beholder":  {Comment: "Beholder is the configuration for the beholder client."},
		"LogLevel":  {Comment: "LogLevel specifies the logging level for service logger"},
		"Pyroscope": {Comment: "Pyroscope is the configuration for pyroscope performance monitoring tool"},
	}
}

func (PyroscopeConfig) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"Enabled": {Comment: "Enabled enables the pyroscope telemetry."},
		"URL":     {Comment: "URL specifies the remote endpoint of pyroscope service"},
	}
}
