// Code generated by mockery v2.53.5. DO NOT EDIT.

package executor_mocks

import (
	types "github.com/smartcontractkit/chainlink-ccv/protocol/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockLeaderElector is an autogenerated mock type for the LeaderElector type
type MockLeaderElector struct {
	mock.Mock
}

type MockLeaderElector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeaderElector) EXPECT() *MockLeaderElector_Expecter {
	return &MockLeaderElector_Expecter{mock: &_m.Mock}
}

// GetDelay provides a mock function with given fields: messageID, destSelector, readyTimestamp
func (_m *MockLeaderElector) GetDelay(messageID types.Bytes32, destSelector types.ChainSelector, readyTimestamp int64) int64 {
	ret := _m.Called(messageID, destSelector, readyTimestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetDelay")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(types.Bytes32, types.ChainSelector, int64) int64); ok {
		r0 = rf(messageID, destSelector, readyTimestamp)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockLeaderElector_GetDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDelay'
type MockLeaderElector_GetDelay_Call struct {
	*mock.Call
}

// GetDelay is a helper method to define mock.On call
//   - messageID types.Bytes32
//   - destSelector types.ChainSelector
//   - readyTimestamp int64
func (_e *MockLeaderElector_Expecter) GetDelay(messageID interface{}, destSelector interface{}, readyTimestamp interface{}) *MockLeaderElector_GetDelay_Call {
	return &MockLeaderElector_GetDelay_Call{Call: _e.mock.On("GetDelay", messageID, destSelector, readyTimestamp)}
}

func (_c *MockLeaderElector_GetDelay_Call) Run(run func(messageID types.Bytes32, destSelector types.ChainSelector, readyTimestamp int64)) *MockLeaderElector_GetDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Bytes32), args[1].(types.ChainSelector), args[2].(int64))
	})
	return _c
}

func (_c *MockLeaderElector_GetDelay_Call) Return(_a0 int64) *MockLeaderElector_GetDelay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderElector_GetDelay_Call) RunAndReturn(run func(types.Bytes32, types.ChainSelector, int64) int64) *MockLeaderElector_GetDelay_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLeaderElector creates a new instance of MockLeaderElector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLeaderElector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLeaderElector {
	mock := &MockLeaderElector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
