// Code generated by github.com/smartcontractkit/chainlink-ccv/tools/configdoc, DO NOT EDIT.

package token

import "github.com/smartcontractkit/chainlink-common/x/config/commentparsing"

func (Config) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"CommitteeConfig":         {Comment: "CommitteeConfig is the generic config needed for SourceReader."},
		"DisableFinalityCheckers": {Comment: "DisableFinalityCheckers lists chain selectors, as strings, whose finality violation checker\nis disabled. Solana needs it: a skipped slot has no block, which the checker reports as a\nmissing block header. Mirrors commit.Config.DisableFinalityCheckers."},
		"Monitoring":              {Comment: "Monitoring contains the monitoring configuration for the token verifier, including Beholder settings.\n\nUnlike the commit (committee) verifier and the executor — which now source monitoring from the\noperator-provided bootstrap config (bootstrap.Config.Monitoring) rather than their JD-shipped app\nconfig — the token verifier intentionally keeps monitoring here, in its app config. It runs in\nlocal app-config mode (app_config_mode = \"local_app_config\") with no JD/DB/keystore; its app\nconfig file is already operator-provided (mounted, not JD-shipped), so this field already\nsatisfies the rule that monitoring must be operator-provided and never delivered via a JD-shipped\napp config."},
		"PyroscopeURL":            {Comment: "PyroscopeURL is the Pyroscope server URL for continuous profiling; empty disables it."},
		"TokenVerifiers":          {Comment: "TokenVerifiers is a list of token verifier configurations. Each entry defines a token verifier instance with its own type, version and configuration."},
	}
}

func (VerifierConfig) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"Type":       {Comment: "Type is the type of the token verifier. You can think of different token verifiers as different\nstrategies for processing token data. For example, you can have a token verifiers for USDC tokens using CCTP\nand different one for processing LINK token."},
		"VerifierID": {Comment: "VerifierID is the unique identifier for this token verifier instance.\nThis allows multiple token verifiers to run on the same node with isolated state."},
		"Version":    {Comment: "Version is the version of the token.VerifierConfig and the matching verifier.Verifier implementation for that config.\nThis is used to determine which version of the verifier to use. Right now, we only have one version\nof the verifier, but in the future, we might have multiple versions.\nThis is a precautionary measure to ensure that we can upgrade the verifier without breaking the existing ones.\nExample would be CCTPv1 using AttestationAPI and CCTPv2 using a different API or completely\ndifferent strategy which requires different configuration and implementation during Verification phase.\n\nExample JSON representation (but any format would work, as long proper marshall/unmarshall is implemented):\n[\n {\n   \"type\": \"cctp\",\n   \"version\": \"2.0\",\n   \"attestationAPI\": \"http://circle.com/attestation\",\n   \"attestationAPITimeout\": \"1s\",\n   \"attestationAPIIntervalMilliseconds\": \"500ms\"\n },\n {\n   \"type\": \"lombard\",\n   \"version\": \"1.0\",\n   \"attestationAPI\": \"http://lombard.com/gohere\",\n   \"attestationAPITimeout\": \"1s\",\n   \"attestationAPIIntervalMilliseconds\": \"500ms\"\n }\n]\nHaving version in that JSON isn't expensive, but it could reduce the risk of breaking the observers in the future."},
	}
}
