// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	protocol "github.com/smartcontractkit/chainlink-ccv/protocol"
	cctp "github.com/smartcontractkit/chainlink-ccv/verifier/token/cctp"
	mock "github.com/stretchr/testify/mock"
)

// CCTPAttestationService is an autogenerated mock type for the AttestationService type
type CCTPAttestationService struct {
	mock.Mock
}

type CCTPAttestationService_Expecter struct {
	mock *mock.Mock
}

func (_m *CCTPAttestationService) EXPECT() *CCTPAttestationService_Expecter {
	return &CCTPAttestationService_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, txHash, message
func (_m *CCTPAttestationService) Fetch(ctx context.Context, txHash protocol.ByteSlice, message protocol.Message) (cctp.Attestation, error) {
	ret := _m.Called(ctx, txHash, message)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 cctp.Attestation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.ByteSlice, protocol.Message) (cctp.Attestation, error)); ok {
		return rf(ctx, txHash, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.ByteSlice, protocol.Message) cctp.Attestation); ok {
		r0 = rf(ctx, txHash, message)
	} else {
		r0 = ret.Get(0).(cctp.Attestation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.ByteSlice, protocol.Message) error); ok {
		r1 = rf(ctx, txHash, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CCTPAttestationService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type CCTPAttestationService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash protocol.ByteSlice
//   - message protocol.Message
func (_e *CCTPAttestationService_Expecter) Fetch(ctx interface{}, txHash interface{}, message interface{}) *CCTPAttestationService_Fetch_Call {
	return &CCTPAttestationService_Fetch_Call{Call: _e.mock.On("Fetch", ctx, txHash, message)}
}

func (_c *CCTPAttestationService_Fetch_Call) Run(run func(ctx context.Context, txHash protocol.ByteSlice, message protocol.Message)) *CCTPAttestationService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.ByteSlice), args[2].(protocol.Message))
	})
	return _c
}

func (_c *CCTPAttestationService_Fetch_Call) Return(_a0 cctp.Attestation, _a1 error) *CCTPAttestationService_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CCTPAttestationService_Fetch_Call) RunAndReturn(run func(context.Context, protocol.ByteSlice, protocol.Message) (cctp.Attestation, error)) *CCTPAttestationService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewCCTPAttestationService creates a new instance of CCTPAttestationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCCTPAttestationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CCTPAttestationService {
	mock := &CCTPAttestationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
