// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	lombard "github.com/smartcontractkit/chainlink-ccv/verifier/token/lombard"
	mock "github.com/stretchr/testify/mock"

	verifier "github.com/smartcontractkit/chainlink-ccv/verifier"
)

// LombardAttestationService is an autogenerated mock type for the AttestationService type
type LombardAttestationService struct {
	mock.Mock
}

type LombardAttestationService_Expecter struct {
	mock *mock.Mock
}

func (_m *LombardAttestationService) EXPECT() *LombardAttestationService_Expecter {
	return &LombardAttestationService_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, tasks
func (_m *LombardAttestationService) Fetch(ctx context.Context, tasks []verifier.VerificationTask) (map[string]lombard.Attestation, error) {
	ret := _m.Called(ctx, tasks)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 map[string]lombard.Attestation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []verifier.VerificationTask) (map[string]lombard.Attestation, error)); ok {
		return rf(ctx, tasks)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []verifier.VerificationTask) map[string]lombard.Attestation); ok {
		r0 = rf(ctx, tasks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]lombard.Attestation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []verifier.VerificationTask) error); ok {
		r1 = rf(ctx, tasks)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LombardAttestationService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type LombardAttestationService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - tasks []verifier.VerificationTask
func (_e *LombardAttestationService_Expecter) Fetch(ctx interface{}, tasks interface{}) *LombardAttestationService_Fetch_Call {
	return &LombardAttestationService_Fetch_Call{Call: _e.mock.On("Fetch", ctx, tasks)}
}

func (_c *LombardAttestationService_Fetch_Call) Run(run func(ctx context.Context, tasks []verifier.VerificationTask)) *LombardAttestationService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]verifier.VerificationTask))
	})
	return _c
}

func (_c *LombardAttestationService_Fetch_Call) Return(_a0 map[string]lombard.Attestation, _a1 error) *LombardAttestationService_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LombardAttestationService_Fetch_Call) RunAndReturn(run func(context.Context, []verifier.VerificationTask) (map[string]lombard.Attestation, error)) *LombardAttestationService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewLombardAttestationService creates a new instance of LombardAttestationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLombardAttestationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LombardAttestationService {
	mock := &LombardAttestationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
