name: 'Build Docker Images with Justfile'
description: 'Build Docker images using just build-docker-dev and load them to local Docker daemon'

inputs:
  justfile-target:
    description: 'The Justfile target to run (default: build-docker-dev)'
    required: false
    default: 'build-docker-dev'
  cache-from:
    description: 'Docker cache from images (comma-separated)'
    required: false
    default: ''
  cache-to:
    description: 'Docker cache to images (comma-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    - name: Set up Just
      uses: extractions/setup-just@v2
      with:
        just-version: '1.30.0'

    - name: Build Docker images
      shell: bash
      run: |
        # Set up cache options if provided
        CACHE_OPTS=""
        if [ -n "${{ inputs.cache-from }}" ]; then
          CACHE_OPTS="$CACHE_OPTS --cache-from=${{ inputs.cache-from }}"
        fi
        if [ -n "${{ inputs.cache-to }}" ]; then
          CACHE_OPTS="$CACHE_OPTS --cache-to=${{ inputs.cache-to }}"
        fi
        
        # Build using Justfile
        just ${{ inputs.justfile-target }} $CACHE_OPTS
        
        # Load all built images to local Docker daemon
        echo "Loading built images to local Docker daemon..."
        docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "<none>" | while read image; do
          echo "Loading $image"
          docker save "$image" | docker load
        done
      env:
        DOCKER_BUILDKIT: 1

    - name: Verify loaded images
      shell: bash
      run: |
        echo "Images available in local Docker daemon:"
        docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"