// Code generated by github.com/smartcontractkit/chainlink-ccv/tools/configdoc, DO NOT EDIT.

package chainaccess

import "github.com/smartcontractkit/chainlink-common/x/config/commentparsing"

func (CommitteeConfig) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"OnRampAddresses":    {Comment: "OnRampAddresses is a map the addresses of the on ramps for each chain selector."},
		"RMNRemoteAddresses": {Comment: "RMNRemoteAddresses is a map of RMN Remote contract addresses for each chain selector.\nDEPRECATED: the RMN Remote address is derived from each OnRamp's on-chain static config,\nwhich is authoritative. This field is retained so that job specs written before the\nderivation cutover still decode; when an entry is present and disagrees with the derived\naddress, a warning is logged and the derived address is used. Remove once deployed specs\nno longer carry it."},
	}
}

func (DestinationChainConfig) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"OffRampAddress":     {Comment: "OffRampAddress is the address of the OffRamp contract on the destination chain."},
		"RmnAddress":         {Comment: "RmnAddress is the address of the RMN Remote contract on the destination chain.\nDEPRECATED: the RMN Remote address is derived from the OffRamp's on-chain static config,\nwhich is authoritative. This field is retained so that job specs written before the\nderivation cutover still decode; when set and it disagrees with the derived address, a\nwarning is logged and the derived address is used. Remove once deployed specs no longer\ncarry it."},
		"TransmitterKeyName": {Comment: "TransmitterKeyName is the family-specific keystore key name used to sign and submit\ntransactions to the OffRamp on this chain. If empty, accessors fall back to their\nfamily's default transmitter key (defined by each family's transmitter package)."},
	}
}
