// Code generated by mockery v2.53.5. DO NOT EDIT.

package executor_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	protocol "github.com/smartcontractkit/chainlink-ccv/protocol"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// AttemptExecuteMessage provides a mock function with given fields: ctx, message
func (_m *MockExecutor) AttemptExecuteMessage(ctx context.Context, message protocol.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for AttemptExecuteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutor_AttemptExecuteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttemptExecuteMessage'
type MockExecutor_AttemptExecuteMessage_Call struct {
	*mock.Call
}

// AttemptExecuteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message protocol.Message
func (_e *MockExecutor_Expecter) AttemptExecuteMessage(ctx interface{}, message interface{}) *MockExecutor_AttemptExecuteMessage_Call {
	return &MockExecutor_AttemptExecuteMessage_Call{Call: _e.mock.On("AttemptExecuteMessage", ctx, message)}
}

func (_c *MockExecutor_AttemptExecuteMessage_Call) Run(run func(ctx context.Context, message protocol.Message)) *MockExecutor_AttemptExecuteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.Message))
	})
	return _c
}

func (_c *MockExecutor_AttemptExecuteMessage_Call) Return(_a0 error) *MockExecutor_AttemptExecuteMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_AttemptExecuteMessage_Call) RunAndReturn(run func(context.Context, protocol.Message) error) *MockExecutor_AttemptExecuteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CheckValidMessage provides a mock function with given fields: ctx, message
func (_m *MockExecutor) CheckValidMessage(ctx context.Context, message protocol.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for CheckValidMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutor_CheckValidMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckValidMessage'
type MockExecutor_CheckValidMessage_Call struct {
	*mock.Call
}

// CheckValidMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message protocol.Message
func (_e *MockExecutor_Expecter) CheckValidMessage(ctx interface{}, message interface{}) *MockExecutor_CheckValidMessage_Call {
	return &MockExecutor_CheckValidMessage_Call{Call: _e.mock.On("CheckValidMessage", ctx, message)}
}

func (_c *MockExecutor_CheckValidMessage_Call) Run(run func(ctx context.Context, message protocol.Message)) *MockExecutor_CheckValidMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.Message))
	})
	return _c
}

func (_c *MockExecutor_CheckValidMessage_Call) Return(_a0 error) *MockExecutor_CheckValidMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_CheckValidMessage_Call) RunAndReturn(run func(context.Context, protocol.Message) error) *MockExecutor_CheckValidMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageStatus provides a mock function with given fields: ctx, message, currentTime
func (_m *MockExecutor) GetMessageStatus(ctx context.Context, message protocol.Message, currentTime int64) (bool, bool, error) {
	ret := _m.Called(ctx, message, currentTime)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageStatus")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Message, int64) (bool, bool, error)); ok {
		return rf(ctx, message, currentTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Message, int64) bool); ok {
		r0 = rf(ctx, message, currentTime)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.Message, int64) bool); ok {
		r1 = rf(ctx, message, currentTime)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, protocol.Message, int64) error); ok {
		r2 = rf(ctx, message, currentTime)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockExecutor_GetMessageStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageStatus'
type MockExecutor_GetMessageStatus_Call struct {
	*mock.Call
}

// GetMessageStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - message protocol.Message
//   - currentTime int64
func (_e *MockExecutor_Expecter) GetMessageStatus(ctx interface{}, message interface{}, currentTime interface{}) *MockExecutor_GetMessageStatus_Call {
	return &MockExecutor_GetMessageStatus_Call{Call: _e.mock.On("GetMessageStatus", ctx, message, currentTime)}
}

func (_c *MockExecutor_GetMessageStatus_Call) Run(run func(ctx context.Context, message protocol.Message, currentTime int64)) *MockExecutor_GetMessageStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.Message), args[2].(int64))
	})
	return _c
}

func (_c *MockExecutor_GetMessageStatus_Call) Return(_a0 bool, _a1 bool, _a2 error) *MockExecutor_GetMessageStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockExecutor_GetMessageStatus_Call) RunAndReturn(run func(context.Context, protocol.Message, int64) (bool, bool, error)) *MockExecutor_GetMessageStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
