// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"

	v1 "github.com/smartcontractkit/chainlink-protos/chainlink-ccv/committee-verifier/v1"
)

// MockCommitteeBatchWriter is an autogenerated mock type for the CommitteeBatchWriter type
type MockCommitteeBatchWriter struct {
	mock.Mock
}

type MockCommitteeBatchWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitteeBatchWriter) EXPECT() *MockCommitteeBatchWriter_Expecter {
	return &MockCommitteeBatchWriter_Expecter{mock: &_m.Mock}
}

// BatchWriteCommitteeVerifierNodeResult provides a mock function with given fields: ctx, in, opts
func (_m *MockCommitteeBatchWriter) BatchWriteCommitteeVerifierNodeResult(ctx context.Context, in *v1.BatchWriteCommitteeVerifierNodeResultRequest, opts ...grpc.CallOption) (*v1.BatchWriteCommitteeVerifierNodeResultResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BatchWriteCommitteeVerifierNodeResult")
	}

	var r0 *v1.BatchWriteCommitteeVerifierNodeResultResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BatchWriteCommitteeVerifierNodeResultRequest, ...grpc.CallOption) (*v1.BatchWriteCommitteeVerifierNodeResultResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BatchWriteCommitteeVerifierNodeResultRequest, ...grpc.CallOption) *v1.BatchWriteCommitteeVerifierNodeResultResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BatchWriteCommitteeVerifierNodeResultResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.BatchWriteCommitteeVerifierNodeResultRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchWriteCommitteeVerifierNodeResult'
type MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call struct {
	*mock.Call
}

// BatchWriteCommitteeVerifierNodeResult is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.BatchWriteCommitteeVerifierNodeResultRequest
//   - opts ...grpc.CallOption
func (_e *MockCommitteeBatchWriter_Expecter) BatchWriteCommitteeVerifierNodeResult(ctx interface{}, in interface{}, opts ...interface{}) *MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call {
	return &MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call{Call: _e.mock.On("BatchWriteCommitteeVerifierNodeResult",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call) Run(run func(ctx context.Context, in *v1.BatchWriteCommitteeVerifierNodeResultRequest, opts ...grpc.CallOption)) *MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1.BatchWriteCommitteeVerifierNodeResultRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call) Return(_a0 *v1.BatchWriteCommitteeVerifierNodeResultResponse, _a1 error) *MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call) RunAndReturn(run func(context.Context, *v1.BatchWriteCommitteeVerifierNodeResultRequest, ...grpc.CallOption) (*v1.BatchWriteCommitteeVerifierNodeResultResponse, error)) *MockCommitteeBatchWriter_BatchWriteCommitteeVerifierNodeResult_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommitteeBatchWriter creates a new instance of MockCommitteeBatchWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitteeBatchWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitteeBatchWriter {
	mock := &MockCommitteeBatchWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
