with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
resolve-type-alias: false
packages:
    github.com/smartcontractkit/chainlink-ccv/protocol/verifier:
        config:
            dir: verifier/mocks
            outpkg: mocks
        interfaces:
            SourceReader:
    github.com/smartcontractkit/chainlink-ccv/protocol/common:
        config:
            dir: common/mocks
            outpkg: mocks
        interfaces:
            Writer:
