with-expecter: true

dir: common/mocks
outpkg: mocks

packages:
    github.com/smartcontractkit/chainlink-ccv/protocol:
        interfaces:
          ChainStatusManager:
          FinalityViolationChecker:
    github.com/smartcontractkit/chainlink-ccv/protocol/common/chainaccess:
        interfaces:
            HeadTracker:
            SourceReader:
            RMNCurseReader:
