# Default: show available recipes
default:
    just --list

test:
    go test -v ./...

test-coverage:
    go test -v -coverprofile=coverage.out ./...

# Format all go files
fmt:
    golangci-lint fmt

# Run golangci-lint
lint:
    golangci-lint run --output.text.path stdout

mod-tidy:
    go mod tidy

mod-download:
    go mod download
