set fallback

import '../tools/lib/utils.justfile'

# Default: show available recipes
default:
    just --list

test: ensure-go
    go test -v ./...

test-coverage:
    go test -v -coverprofile=coverage.out ./...

# Format all go files
fmt: ensure-golangci-lint
    golangci-lint fmt

# Run golangci-lint
lint: ensure-golangci-lint
    golangci-lint run --output.text.path stdout

mod-tidy: ensure-go
    go mod tidy

mod-tidy: ensure-go
    go mod download
