root = ".."

[build]
cmd = "go build -o /tmp/indexer /app/indexer/cmd"
bin = "/tmp/indexer"
include_dir = ["app"]
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "testdata", ".git"]
