set fallback

import '../tools/lib/utils.justfile'

# Default: show available recipes
default:
    just --list

build:
    docker build -f Dockerfile -t indexer:latest ..

build-backfill:
    cd .. && go build -o indexer/bin/indexer-backfill ./indexer/cmd/backfill/main.go

build-rc:
    docker build -f Dockerfile -t indexer:rc ..

build-dev:
    docker build -f Dockerfile.dev -t indexer:dev ..

publish-rc registry version:
    docker tag indexer:rc {{registry}}/containers/chainlink-ccv-indexer:{{version}}-rc
    docker push {{registry}}/containers/chainlink-ccv-indexer:{{version}}-rc

publish registry version:
    docker tag indexer:latest {{registry}}/containers/chainlink-ccv-indexer:{{version}}
    docker push {{registry}}/containers/chainlink-ccv-indexer:{{version}}

clean:
    docker rmi indexer:latest

clean-dev:
    docker rmi indexer:dev

create-migration name:
    goose create {{name}} sql -dir ./migrations
