set fallback

import '../tools/lib/utils.justfile'

# Default: show available recipes
default:
    just --list

test: ensure-go
    go test -v -race ./...

build-rc:
    docker build -f Dockerfile -t indexer:rc ..

build-dev:
    docker build -f Dockerfile.dev -t indexer:dev ..

publish-rc registry version:
    docker tag indexer:rc {{registry}}/chainlink-ccv-indexer:{{version}}-rc
    docker push {{registry}}/chainlink-ccv-indexer:{{version}}-rc

clean:
    docker rmi indexer:latest

clean-dev:
    docker rmi indexer:dev
