// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: aggregator.proto

package aggregator

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteStatus int32

const (
	WriteStatus_SUCCESS WriteStatus = 0
	WriteStatus_FAILED  WriteStatus = 1
)

// Enum value maps for WriteStatus.
var (
	WriteStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	WriteStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x WriteStatus) Enum() *WriteStatus {
	p := new(WriteStatus)
	*p = x
	return p
}

func (x WriteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aggregator_proto_enumTypes[0].Descriptor()
}

func (WriteStatus) Type() protoreflect.EnumType {
	return &file_aggregator_proto_enumTypes[0]
}

func (x WriteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteStatus.Descriptor instead.
func (WriteStatus) EnumDescriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{0}
}

type BlockCheckpoint struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ChainSelector        uint64                 `protobuf:"varint,1,opt,name=chain_selector,json=chainSelector,proto3" json:"chain_selector,omitempty"`
	FinalizedBlockHeight uint64                 `protobuf:"varint,2,opt,name=finalized_block_height,json=finalizedBlockHeight,proto3" json:"finalized_block_height,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BlockCheckpoint) Reset() {
	*x = BlockCheckpoint{}
	mi := &file_aggregator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCheckpoint) ProtoMessage() {}

func (x *BlockCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCheckpoint.ProtoReflect.Descriptor instead.
func (*BlockCheckpoint) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{0}
}

func (x *BlockCheckpoint) GetChainSelector() uint64 {
	if x != nil {
		return x.ChainSelector
	}
	return 0
}

func (x *BlockCheckpoint) GetFinalizedBlockHeight() uint64 {
	if x != nil {
		return x.FinalizedBlockHeight
	}
	return 0
}

type WriteBlockCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoints   []*BlockCheckpoint     `protobuf:"bytes,1,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBlockCheckpointRequest) Reset() {
	*x = WriteBlockCheckpointRequest{}
	mi := &file_aggregator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBlockCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockCheckpointRequest) ProtoMessage() {}

func (x *WriteBlockCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockCheckpointRequest.ProtoReflect.Descriptor instead.
func (*WriteBlockCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{1}
}

func (x *WriteBlockCheckpointRequest) GetCheckpoints() []*BlockCheckpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

type WriteBlockCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WriteStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=WriteStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBlockCheckpointResponse) Reset() {
	*x = WriteBlockCheckpointResponse{}
	mi := &file_aggregator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBlockCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockCheckpointResponse) ProtoMessage() {}

func (x *WriteBlockCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockCheckpointResponse.ProtoReflect.Descriptor instead.
func (*WriteBlockCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{2}
}

func (x *WriteBlockCheckpointResponse) GetStatus() WriteStatus {
	if x != nil {
		return x.Status
	}
	return WriteStatus_SUCCESS
}

type ReadBlockCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBlockCheckpointRequest) Reset() {
	*x = ReadBlockCheckpointRequest{}
	mi := &file_aggregator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBlockCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBlockCheckpointRequest) ProtoMessage() {}

func (x *ReadBlockCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBlockCheckpointRequest.ProtoReflect.Descriptor instead.
func (*ReadBlockCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{3}
}

type ReadBlockCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoints   []*BlockCheckpoint     `protobuf:"bytes,1,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBlockCheckpointResponse) Reset() {
	*x = ReadBlockCheckpointResponse{}
	mi := &file_aggregator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBlockCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBlockCheckpointResponse) ProtoMessage() {}

func (x *ReadBlockCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBlockCheckpointResponse.ProtoReflect.Descriptor instead.
func (*ReadBlockCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{4}
}

func (x *ReadBlockCheckpointResponse) GetCheckpoints() []*BlockCheckpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

type Message struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Version              uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SourceChainSelector  uint64                 `protobuf:"varint,2,opt,name=source_chain_selector,json=sourceChainSelector,proto3" json:"source_chain_selector,omitempty"`
	DestChainSelector    uint64                 `protobuf:"varint,3,opt,name=dest_chain_selector,json=destChainSelector,proto3" json:"dest_chain_selector,omitempty"`
	SequenceNumber       uint64                 `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	OnRampAddressLength  uint32                 `protobuf:"varint,5,opt,name=on_ramp_address_length,json=onRampAddressLength,proto3" json:"on_ramp_address_length,omitempty"`
	OnRampAddress        []byte                 `protobuf:"bytes,6,opt,name=on_ramp_address,json=onRampAddress,proto3" json:"on_ramp_address,omitempty"`
	OffRampAddressLength uint32                 `protobuf:"varint,7,opt,name=off_ramp_address_length,json=offRampAddressLength,proto3" json:"off_ramp_address_length,omitempty"`
	OffRampAddress       []byte                 `protobuf:"bytes,8,opt,name=off_ramp_address,json=offRampAddress,proto3" json:"off_ramp_address,omitempty"`
	Finality             uint32                 `protobuf:"varint,9,opt,name=finality,proto3" json:"finality,omitempty"`
	SenderLength         uint32                 `protobuf:"varint,10,opt,name=sender_length,json=senderLength,proto3" json:"sender_length,omitempty"`
	Sender               []byte                 `protobuf:"bytes,11,opt,name=sender,proto3" json:"sender,omitempty"`
	ReceiverLength       uint32                 `protobuf:"varint,12,opt,name=receiver_length,json=receiverLength,proto3" json:"receiver_length,omitempty"`
	Receiver             []byte                 `protobuf:"bytes,13,opt,name=receiver,proto3" json:"receiver,omitempty"`
	DestBlobLength       uint32                 `protobuf:"varint,14,opt,name=dest_blob_length,json=destBlobLength,proto3" json:"dest_blob_length,omitempty"`
	DestBlob             []byte                 `protobuf:"bytes,15,opt,name=dest_blob,json=destBlob,proto3" json:"dest_blob,omitempty"`
	TokenTransferLength  uint32                 `protobuf:"varint,16,opt,name=token_transfer_length,json=tokenTransferLength,proto3" json:"token_transfer_length,omitempty"`
	TokenTransfer        []byte                 `protobuf:"bytes,17,opt,name=token_transfer,json=tokenTransfer,proto3" json:"token_transfer,omitempty"`
	DataLength           uint32                 `protobuf:"varint,18,opt,name=data_length,json=dataLength,proto3" json:"data_length,omitempty"`
	Data                 []byte                 `protobuf:"bytes,19,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_aggregator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Message) GetSourceChainSelector() uint64 {
	if x != nil {
		return x.SourceChainSelector
	}
	return 0
}

func (x *Message) GetDestChainSelector() uint64 {
	if x != nil {
		return x.DestChainSelector
	}
	return 0
}

func (x *Message) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Message) GetOnRampAddressLength() uint32 {
	if x != nil {
		return x.OnRampAddressLength
	}
	return 0
}

func (x *Message) GetOnRampAddress() []byte {
	if x != nil {
		return x.OnRampAddress
	}
	return nil
}

func (x *Message) GetOffRampAddressLength() uint32 {
	if x != nil {
		return x.OffRampAddressLength
	}
	return 0
}

func (x *Message) GetOffRampAddress() []byte {
	if x != nil {
		return x.OffRampAddress
	}
	return nil
}

func (x *Message) GetFinality() uint32 {
	if x != nil {
		return x.Finality
	}
	return 0
}

func (x *Message) GetSenderLength() uint32 {
	if x != nil {
		return x.SenderLength
	}
	return 0
}

func (x *Message) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Message) GetReceiverLength() uint32 {
	if x != nil {
		return x.ReceiverLength
	}
	return 0
}

func (x *Message) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Message) GetDestBlobLength() uint32 {
	if x != nil {
		return x.DestBlobLength
	}
	return 0
}

func (x *Message) GetDestBlob() []byte {
	if x != nil {
		return x.DestBlob
	}
	return nil
}

func (x *Message) GetTokenTransferLength() uint32 {
	if x != nil {
		return x.TokenTransferLength
	}
	return 0
}

func (x *Message) GetTokenTransfer() []byte {
	if x != nil {
		return x.TokenTransfer
	}
	return nil
}

func (x *Message) GetDataLength() uint32 {
	if x != nil {
		return x.DataLength
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReceiptBlob struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Issuer            []byte                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	DestGasLimit      uint64                 `protobuf:"varint,2,opt,name=dest_gas_limit,json=destGasLimit,proto3" json:"dest_gas_limit,omitempty"`
	DestBytesOverhead uint32                 `protobuf:"varint,3,opt,name=dest_bytes_overhead,json=destBytesOverhead,proto3" json:"dest_bytes_overhead,omitempty"`
	Blob              []byte                 `protobuf:"bytes,4,opt,name=blob,proto3" json:"blob,omitempty"`
	ExtraArgs         []byte                 `protobuf:"bytes,5,opt,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiptBlob) Reset() {
	*x = ReceiptBlob{}
	mi := &file_aggregator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptBlob) ProtoMessage() {}

func (x *ReceiptBlob) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptBlob.ProtoReflect.Descriptor instead.
func (*ReceiptBlob) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiptBlob) GetIssuer() []byte {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *ReceiptBlob) GetDestGasLimit() uint64 {
	if x != nil {
		return x.DestGasLimit
	}
	return 0
}

func (x *ReceiptBlob) GetDestBytesOverhead() uint32 {
	if x != nil {
		return x.DestBytesOverhead
	}
	return 0
}

func (x *ReceiptBlob) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *ReceiptBlob) GetExtraArgs() []byte {
	if x != nil {
		return x.ExtraArgs
	}
	return nil
}

type MessageWithCCVNodeData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MessageId             []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SourceVerifierAddress []byte                 `protobuf:"bytes,2,opt,name=source_verifier_address,json=sourceVerifierAddress,proto3" json:"source_verifier_address,omitempty"`
	DestVerifierAddress   []byte                 `protobuf:"bytes,3,opt,name=dest_verifier_address,json=destVerifierAddress,proto3" json:"dest_verifier_address,omitempty"`
	// ccv_data is the signature from the commit verifier node of the message data and the blob data
	CcvData []byte `protobuf:"bytes,4,opt,name=ccv_data,json=ccvData,proto3" json:"ccv_data,omitempty"`
	// blob_data is the encoded nonce from the source chain
	BlobData      []byte         `protobuf:"bytes,5,opt,name=blob_data,json=blobData,proto3" json:"blob_data,omitempty"`
	Timestamp     int64          `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       *Message       `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	ReceiptBlobs  []*ReceiptBlob `protobuf:"bytes,8,rep,name=receipt_blobs,json=receiptBlobs,proto3" json:"receipt_blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithCCVNodeData) Reset() {
	*x = MessageWithCCVNodeData{}
	mi := &file_aggregator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithCCVNodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithCCVNodeData) ProtoMessage() {}

func (x *MessageWithCCVNodeData) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithCCVNodeData.ProtoReflect.Descriptor instead.
func (*MessageWithCCVNodeData) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{7}
}

func (x *MessageWithCCVNodeData) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageWithCCVNodeData) GetSourceVerifierAddress() []byte {
	if x != nil {
		return x.SourceVerifierAddress
	}
	return nil
}

func (x *MessageWithCCVNodeData) GetDestVerifierAddress() []byte {
	if x != nil {
		return x.DestVerifierAddress
	}
	return nil
}

func (x *MessageWithCCVNodeData) GetCcvData() []byte {
	if x != nil {
		return x.CcvData
	}
	return nil
}

func (x *MessageWithCCVNodeData) GetBlobData() []byte {
	if x != nil {
		return x.BlobData
	}
	return nil
}

func (x *MessageWithCCVNodeData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageWithCCVNodeData) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageWithCCVNodeData) GetReceiptBlobs() []*ReceiptBlob {
	if x != nil {
		return x.ReceiptBlobs
	}
	return nil
}

type MessageWithCCVData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Message               *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SourceVerifierAddress []byte                 `protobuf:"bytes,2,opt,name=source_verifier_address,json=sourceVerifierAddress,proto3" json:"source_verifier_address,omitempty"`
	DestVerifierAddress   []byte                 `protobuf:"bytes,3,opt,name=dest_verifier_address,json=destVerifierAddress,proto3" json:"dest_verifier_address,omitempty"`
	CcvData               []byte                 `protobuf:"bytes,4,opt,name=ccv_data,json=ccvData,proto3" json:"ccv_data,omitempty"`
	Timestamp             int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MessageWithCCVData) Reset() {
	*x = MessageWithCCVData{}
	mi := &file_aggregator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithCCVData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithCCVData) ProtoMessage() {}

func (x *MessageWithCCVData) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithCCVData.ProtoReflect.Descriptor instead.
func (*MessageWithCCVData) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{8}
}

func (x *MessageWithCCVData) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageWithCCVData) GetSourceVerifierAddress() []byte {
	if x != nil {
		return x.SourceVerifierAddress
	}
	return nil
}

func (x *MessageWithCCVData) GetDestVerifierAddress() []byte {
	if x != nil {
		return x.DestVerifierAddress
	}
	return nil
}

func (x *MessageWithCCVData) GetCcvData() []byte {
	if x != nil {
		return x.CcvData
	}
	return nil
}

func (x *MessageWithCCVData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BatchWriteCommitCCVNodeDataRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Requests      []*WriteCommitCCVNodeDataRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchWriteCommitCCVNodeDataRequest) Reset() {
	*x = BatchWriteCommitCCVNodeDataRequest{}
	mi := &file_aggregator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchWriteCommitCCVNodeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchWriteCommitCCVNodeDataRequest) ProtoMessage() {}

func (x *BatchWriteCommitCCVNodeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchWriteCommitCCVNodeDataRequest.ProtoReflect.Descriptor instead.
func (*BatchWriteCommitCCVNodeDataRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{9}
}

func (x *BatchWriteCommitCCVNodeDataRequest) GetRequests() []*WriteCommitCCVNodeDataRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchWriteCommitCCVNodeDataResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Responses     []*WriteCommitCCVNodeDataResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Errors        []*status.Status                  `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchWriteCommitCCVNodeDataResponse) Reset() {
	*x = BatchWriteCommitCCVNodeDataResponse{}
	mi := &file_aggregator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchWriteCommitCCVNodeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchWriteCommitCCVNodeDataResponse) ProtoMessage() {}

func (x *BatchWriteCommitCCVNodeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchWriteCommitCCVNodeDataResponse.ProtoReflect.Descriptor instead.
func (*BatchWriteCommitCCVNodeDataResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{10}
}

func (x *BatchWriteCommitCCVNodeDataResponse) GetResponses() []*WriteCommitCCVNodeDataResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchWriteCommitCCVNodeDataResponse) GetErrors() []*status.Status {
	if x != nil {
		return x.Errors
	}
	return nil
}

type WriteCommitCCVNodeDataRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CcvNodeData   *MessageWithCCVNodeData `protobuf:"bytes,1,opt,name=ccv_node_data,json=ccvNodeData,proto3" json:"ccv_node_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCommitCCVNodeDataRequest) Reset() {
	*x = WriteCommitCCVNodeDataRequest{}
	mi := &file_aggregator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCommitCCVNodeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCommitCCVNodeDataRequest) ProtoMessage() {}

func (x *WriteCommitCCVNodeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCommitCCVNodeDataRequest.ProtoReflect.Descriptor instead.
func (*WriteCommitCCVNodeDataRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{11}
}

func (x *WriteCommitCCVNodeDataRequest) GetCcvNodeData() *MessageWithCCVNodeData {
	if x != nil {
		return x.CcvNodeData
	}
	return nil
}

type WriteCommitCCVNodeDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WriteStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=WriteStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCommitCCVNodeDataResponse) Reset() {
	*x = WriteCommitCCVNodeDataResponse{}
	mi := &file_aggregator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCommitCCVNodeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCommitCCVNodeDataResponse) ProtoMessage() {}

func (x *WriteCommitCCVNodeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCommitCCVNodeDataResponse.ProtoReflect.Descriptor instead.
func (*WriteCommitCCVNodeDataResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{12}
}

func (x *WriteCommitCCVNodeDataResponse) GetStatus() WriteStatus {
	if x != nil {
		return x.Status
	}
	return WriteStatus_SUCCESS
}

type ReadCommitCCVNodeDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCommitCCVNodeDataRequest) Reset() {
	*x = ReadCommitCCVNodeDataRequest{}
	mi := &file_aggregator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCommitCCVNodeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCommitCCVNodeDataRequest) ProtoMessage() {}

func (x *ReadCommitCCVNodeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCommitCCVNodeDataRequest.ProtoReflect.Descriptor instead.
func (*ReadCommitCCVNodeDataRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{13}
}

func (x *ReadCommitCCVNodeDataRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *ReadCommitCCVNodeDataRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type ReadCommitCCVNodeDataResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CcvNodeData   *MessageWithCCVNodeData `protobuf:"bytes,1,opt,name=ccv_node_data,json=ccvNodeData,proto3" json:"ccv_node_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCommitCCVNodeDataResponse) Reset() {
	*x = ReadCommitCCVNodeDataResponse{}
	mi := &file_aggregator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCommitCCVNodeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCommitCCVNodeDataResponse) ProtoMessage() {}

func (x *ReadCommitCCVNodeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCommitCCVNodeDataResponse.ProtoReflect.Descriptor instead.
func (*ReadCommitCCVNodeDataResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{14}
}

func (x *ReadCommitCCVNodeDataResponse) GetCcvNodeData() *MessageWithCCVNodeData {
	if x != nil {
		return x.CcvNodeData
	}
	return nil
}

type GetCCVDataForMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCCVDataForMessageRequest) Reset() {
	*x = GetCCVDataForMessageRequest{}
	mi := &file_aggregator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCCVDataForMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCCVDataForMessageRequest) ProtoMessage() {}

func (x *GetCCVDataForMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCCVDataForMessageRequest.ProtoReflect.Descriptor instead.
func (*GetCCVDataForMessageRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{15}
}

func (x *GetCCVDataForMessageRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type GetMessagesSinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         int64                  `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesSinceRequest) Reset() {
	*x = GetMessagesSinceRequest{}
	mi := &file_aggregator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesSinceRequest) ProtoMessage() {}

func (x *GetMessagesSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesSinceRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesSinceRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{16}
}

func (x *GetMessagesSinceRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *GetMessagesSinceRequest) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

type GetMessagesSinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MessageWithCCVData  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesSinceResponse) Reset() {
	*x = GetMessagesSinceResponse{}
	mi := &file_aggregator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesSinceResponse) ProtoMessage() {}

func (x *GetMessagesSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesSinceResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesSinceResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{17}
}

func (x *GetMessagesSinceResponse) GetResults() []*MessageWithCCVData {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetMessagesSinceResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

var File_aggregator_proto protoreflect.FileDescriptor

const file_aggregator_proto_rawDesc = "" +
	"\n" +
	"\x10aggregator.proto\x1a\x17google/rpc/status.proto\"n\n" +
	"\x0fBlockCheckpoint\x12%\n" +
	"\x0echain_selector\x18\x01 \x01(\x04R\rchainSelector\x124\n" +
	"\x16finalized_block_height\x18\x02 \x01(\x04R\x14finalizedBlockHeight\"Q\n" +
	"\x1bWriteBlockCheckpointRequest\x122\n" +
	"\vcheckpoints\x18\x01 \x03(\v2\x10.BlockCheckpointR\vcheckpoints\"D\n" +
	"\x1cWriteBlockCheckpointResponse\x12$\n" +
	"\x06status\x18\x01 \x01(\x0e2\f.WriteStatusR\x06status\"\x1c\n" +
	"\x1aReadBlockCheckpointRequest\"Q\n" +
	"\x1bReadBlockCheckpointResponse\x122\n" +
	"\vcheckpoints\x18\x01 \x03(\v2\x10.BlockCheckpointR\vcheckpoints\"\xe3\x05\n" +
	"\aMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x122\n" +
	"\x15source_chain_selector\x18\x02 \x01(\x04R\x13sourceChainSelector\x12.\n" +
	"\x13dest_chain_selector\x18\x03 \x01(\x04R\x11destChainSelector\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x04R\x0esequenceNumber\x123\n" +
	"\x16on_ramp_address_length\x18\x05 \x01(\rR\x13onRampAddressLength\x12&\n" +
	"\x0fon_ramp_address\x18\x06 \x01(\fR\ronRampAddress\x125\n" +
	"\x17off_ramp_address_length\x18\a \x01(\rR\x14offRampAddressLength\x12(\n" +
	"\x10off_ramp_address\x18\b \x01(\fR\x0eoffRampAddress\x12\x1a\n" +
	"\bfinality\x18\t \x01(\rR\bfinality\x12#\n" +
	"\rsender_length\x18\n" +
	" \x01(\rR\fsenderLength\x12\x16\n" +
	"\x06sender\x18\v \x01(\fR\x06sender\x12'\n" +
	"\x0freceiver_length\x18\f \x01(\rR\x0ereceiverLength\x12\x1a\n" +
	"\breceiver\x18\r \x01(\fR\breceiver\x12(\n" +
	"\x10dest_blob_length\x18\x0e \x01(\rR\x0edestBlobLength\x12\x1b\n" +
	"\tdest_blob\x18\x0f \x01(\fR\bdestBlob\x122\n" +
	"\x15token_transfer_length\x18\x10 \x01(\rR\x13tokenTransferLength\x12%\n" +
	"\x0etoken_transfer\x18\x11 \x01(\fR\rtokenTransfer\x12\x1f\n" +
	"\vdata_length\x18\x12 \x01(\rR\n" +
	"dataLength\x12\x12\n" +
	"\x04data\x18\x13 \x01(\fR\x04data\"\xae\x01\n" +
	"\vReceiptBlob\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\fR\x06issuer\x12$\n" +
	"\x0edest_gas_limit\x18\x02 \x01(\x04R\fdestGasLimit\x12.\n" +
	"\x13dest_bytes_overhead\x18\x03 \x01(\rR\x11destBytesOverhead\x12\x12\n" +
	"\x04blob\x18\x04 \x01(\fR\x04blob\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x05 \x01(\fR\textraArgs\"\xd0\x02\n" +
	"\x16MessageWithCCVNodeData\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x126\n" +
	"\x17source_verifier_address\x18\x02 \x01(\fR\x15sourceVerifierAddress\x122\n" +
	"\x15dest_verifier_address\x18\x03 \x01(\fR\x13destVerifierAddress\x12\x19\n" +
	"\bccv_data\x18\x04 \x01(\fR\accvData\x12\x1b\n" +
	"\tblob_data\x18\x05 \x01(\fR\bblobData\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\"\n" +
	"\amessage\x18\a \x01(\v2\b.MessageR\amessage\x121\n" +
	"\rreceipt_blobs\x18\b \x03(\v2\f.ReceiptBlobR\freceiptBlobs\"\xdd\x01\n" +
	"\x12MessageWithCCVData\x12\"\n" +
	"\amessage\x18\x01 \x01(\v2\b.MessageR\amessage\x126\n" +
	"\x17source_verifier_address\x18\x02 \x01(\fR\x15sourceVerifierAddress\x122\n" +
	"\x15dest_verifier_address\x18\x03 \x01(\fR\x13destVerifierAddress\x12\x19\n" +
	"\bccv_data\x18\x04 \x01(\fR\accvData\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"`\n" +
	"\"BatchWriteCommitCCVNodeDataRequest\x12:\n" +
	"\brequests\x18\x01 \x03(\v2\x1e.WriteCommitCCVNodeDataRequestR\brequests\"\x90\x01\n" +
	"#BatchWriteCommitCCVNodeDataResponse\x12=\n" +
	"\tresponses\x18\x01 \x03(\v2\x1f.WriteCommitCCVNodeDataResponseR\tresponses\x12*\n" +
	"\x06errors\x18\x02 \x03(\v2\x12.google.rpc.StatusR\x06errors\"\\\n" +
	"\x1dWriteCommitCCVNodeDataRequest\x12;\n" +
	"\rccv_node_data\x18\x01 \x01(\v2\x17.MessageWithCCVNodeDataR\vccvNodeData\"F\n" +
	"\x1eWriteCommitCCVNodeDataResponse\x12$\n" +
	"\x06status\x18\x01 \x01(\x0e2\f.WriteStatusR\x06status\"W\n" +
	"\x1cReadCommitCCVNodeDataRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\"\\\n" +
	"\x1dReadCommitCCVNodeDataResponse\x12;\n" +
	"\rccv_node_data\x18\x01 \x01(\v2\x17.MessageWithCCVNodeDataR\vccvNodeData\"<\n" +
	"\x1bGetCCVDataForMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\"N\n" +
	"\x17GetMessagesSinceRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x03R\x05since\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\"h\n" +
	"\x18GetMessagesSinceResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.MessageWithCCVDataR\aresults\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken*&\n" +
	"\vWriteStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x012\xd0\x03\n" +
	"\n" +
	"Aggregator\x12Y\n" +
	"\x16WriteCommitCCVNodeData\x12\x1e.WriteCommitCCVNodeDataRequest\x1a\x1f.WriteCommitCCVNodeDataResponse\x12h\n" +
	"\x1bBatchWriteCommitCCVNodeData\x12#.BatchWriteCommitCCVNodeDataRequest\x1a$.BatchWriteCommitCCVNodeDataResponse\x12V\n" +
	"\x15ReadCommitCCVNodeData\x12\x1d.ReadCommitCCVNodeDataRequest\x1a\x1e.ReadCommitCCVNodeDataResponse\x12S\n" +
	"\x14WriteBlockCheckpoint\x12\x1c.WriteBlockCheckpointRequest\x1a\x1d.WriteBlockCheckpointResponse\x12P\n" +
	"\x13ReadBlockCheckpoint\x12\x1b.ReadBlockCheckpointRequest\x1a\x1c.ReadBlockCheckpointResponse2\x9d\x01\n" +
	"\aCCVData\x12I\n" +
	"\x14GetCCVDataForMessage\x12\x1c.GetCCVDataForMessageRequest\x1a\x13.MessageWithCCVData\x12G\n" +
	"\x10GetMessagesSince\x12\x18.GetMessagesSinceRequest\x1a\x19.GetMessagesSinceResponseB\x0fZ\rpb/aggregatorb\x06proto3"

var (
	file_aggregator_proto_rawDescOnce sync.Once
	file_aggregator_proto_rawDescData []byte
)

func file_aggregator_proto_rawDescGZIP() []byte {
	file_aggregator_proto_rawDescOnce.Do(func() {
		file_aggregator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggregator_proto_rawDesc), len(file_aggregator_proto_rawDesc)))
	})
	return file_aggregator_proto_rawDescData
}

var file_aggregator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aggregator_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_aggregator_proto_goTypes = []any{
	(WriteStatus)(0),                            // 0: WriteStatus
	(*BlockCheckpoint)(nil),                     // 1: BlockCheckpoint
	(*WriteBlockCheckpointRequest)(nil),         // 2: WriteBlockCheckpointRequest
	(*WriteBlockCheckpointResponse)(nil),        // 3: WriteBlockCheckpointResponse
	(*ReadBlockCheckpointRequest)(nil),          // 4: ReadBlockCheckpointRequest
	(*ReadBlockCheckpointResponse)(nil),         // 5: ReadBlockCheckpointResponse
	(*Message)(nil),                             // 6: Message
	(*ReceiptBlob)(nil),                         // 7: ReceiptBlob
	(*MessageWithCCVNodeData)(nil),              // 8: MessageWithCCVNodeData
	(*MessageWithCCVData)(nil),                  // 9: MessageWithCCVData
	(*BatchWriteCommitCCVNodeDataRequest)(nil),  // 10: BatchWriteCommitCCVNodeDataRequest
	(*BatchWriteCommitCCVNodeDataResponse)(nil), // 11: BatchWriteCommitCCVNodeDataResponse
	(*WriteCommitCCVNodeDataRequest)(nil),       // 12: WriteCommitCCVNodeDataRequest
	(*WriteCommitCCVNodeDataResponse)(nil),      // 13: WriteCommitCCVNodeDataResponse
	(*ReadCommitCCVNodeDataRequest)(nil),        // 14: ReadCommitCCVNodeDataRequest
	(*ReadCommitCCVNodeDataResponse)(nil),       // 15: ReadCommitCCVNodeDataResponse
	(*GetCCVDataForMessageRequest)(nil),         // 16: GetCCVDataForMessageRequest
	(*GetMessagesSinceRequest)(nil),             // 17: GetMessagesSinceRequest
	(*GetMessagesSinceResponse)(nil),            // 18: GetMessagesSinceResponse
	(*status.Status)(nil),                       // 19: google.rpc.Status
}
var file_aggregator_proto_depIdxs = []int32{
	1,  // 0: WriteBlockCheckpointRequest.checkpoints:type_name -> BlockCheckpoint
	0,  // 1: WriteBlockCheckpointResponse.status:type_name -> WriteStatus
	1,  // 2: ReadBlockCheckpointResponse.checkpoints:type_name -> BlockCheckpoint
	6,  // 3: MessageWithCCVNodeData.message:type_name -> Message
	7,  // 4: MessageWithCCVNodeData.receipt_blobs:type_name -> ReceiptBlob
	6,  // 5: MessageWithCCVData.message:type_name -> Message
	12, // 6: BatchWriteCommitCCVNodeDataRequest.requests:type_name -> WriteCommitCCVNodeDataRequest
	13, // 7: BatchWriteCommitCCVNodeDataResponse.responses:type_name -> WriteCommitCCVNodeDataResponse
	19, // 8: BatchWriteCommitCCVNodeDataResponse.errors:type_name -> google.rpc.Status
	8,  // 9: WriteCommitCCVNodeDataRequest.ccv_node_data:type_name -> MessageWithCCVNodeData
	0,  // 10: WriteCommitCCVNodeDataResponse.status:type_name -> WriteStatus
	8,  // 11: ReadCommitCCVNodeDataResponse.ccv_node_data:type_name -> MessageWithCCVNodeData
	9,  // 12: GetMessagesSinceResponse.results:type_name -> MessageWithCCVData
	12, // 13: Aggregator.WriteCommitCCVNodeData:input_type -> WriteCommitCCVNodeDataRequest
	10, // 14: Aggregator.BatchWriteCommitCCVNodeData:input_type -> BatchWriteCommitCCVNodeDataRequest
	14, // 15: Aggregator.ReadCommitCCVNodeData:input_type -> ReadCommitCCVNodeDataRequest
	2,  // 16: Aggregator.WriteBlockCheckpoint:input_type -> WriteBlockCheckpointRequest
	4,  // 17: Aggregator.ReadBlockCheckpoint:input_type -> ReadBlockCheckpointRequest
	16, // 18: CCVData.GetCCVDataForMessage:input_type -> GetCCVDataForMessageRequest
	17, // 19: CCVData.GetMessagesSince:input_type -> GetMessagesSinceRequest
	13, // 20: Aggregator.WriteCommitCCVNodeData:output_type -> WriteCommitCCVNodeDataResponse
	11, // 21: Aggregator.BatchWriteCommitCCVNodeData:output_type -> BatchWriteCommitCCVNodeDataResponse
	15, // 22: Aggregator.ReadCommitCCVNodeData:output_type -> ReadCommitCCVNodeDataResponse
	3,  // 23: Aggregator.WriteBlockCheckpoint:output_type -> WriteBlockCheckpointResponse
	5,  // 24: Aggregator.ReadBlockCheckpoint:output_type -> ReadBlockCheckpointResponse
	9,  // 25: CCVData.GetCCVDataForMessage:output_type -> MessageWithCCVData
	18, // 26: CCVData.GetMessagesSince:output_type -> GetMessagesSinceResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_aggregator_proto_init() }
func file_aggregator_proto_init() {
	if File_aggregator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggregator_proto_rawDesc), len(file_aggregator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_aggregator_proto_goTypes,
		DependencyIndexes: file_aggregator_proto_depIdxs,
		EnumInfos:         file_aggregator_proto_enumTypes,
		MessageInfos:      file_aggregator_proto_msgTypes,
	}.Build()
	File_aggregator_proto = out.File
	file_aggregator_proto_goTypes = nil
	file_aggregator_proto_depIdxs = nil
}
