root = ".."

[build]
cmd = "go build -o ./tmp/verifier /app/cmd/verifier/main.go"
bin = "tmp/verifier"
include_dir = ["app"]
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "testdata", ".git"]
