package logpollerschema_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/smartcontractkit/chainlink-ccv/tools/logpollerschema"
)

// A trimmed pg_dump standing in for the node's output: two LogPoller objects, the
// sequence whose doubled-`evm` name defeats a naive pattern, and two objects that
// belong to the node and must be filtered out.
const testRef = "abc1234"

const sampleDump = `SET statement_timeout = 0;

--
-- Name: evm; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA evm;

--
-- Name: f_log_poller_filter_hash(text); Type: FUNCTION; Schema: evm; Owner: -
--

CREATE FUNCTION evm.f_log_poller_filter_hash(name text) RETURNS bigint
    LANGUAGE sql IMMUTABLE
    AS $_$SELECT hashtextextended(name, 0)$_$;

CREATE TABLE evm.log_poller_filters (
    id bigint NOT NULL
);

CREATE SEQUENCE evm.evm_log_poller_filters_id_seq
    START WITH 1;

CREATE TABLE evm.heads (
    id bigint NOT NULL
);

CREATE TABLE evm.upkeep_states (
    id bigint NOT NULL
);
`

func TestGenerate_KeepsLogPollerObjectsOnly(t *testing.T) {
	t.Parallel()

	got, err := logpollerschema.Generate([]byte(sampleDump), testRef)
	require.NoError(t, err)
	out := string(got)

	for _, want := range []string{
		"CREATE SCHEMA evm;",
		"evm.f_log_poller_filter_hash",
		"evm.log_poller_filters",
		// Without this the file references a sequence it never creates.
		"CREATE SEQUENCE evm.evm_log_poller_filters_id_seq",
	} {
		assert.Containsf(t, out, want, "%s must be generated", want)
	}

	for _, unwanted := range []string{"evm.heads", "evm.upkeep_states", "SET statement_timeout"} {
		assert.NotContainsf(t, out, unwanted, "%s belongs to the node, not CCV", unwanted)
	}
}

func TestGenerate_FencesDollarQuotedBodies(t *testing.T) {
	t.Parallel()

	got, err := logpollerschema.Generate([]byte(sampleDump), testRef)
	require.NoError(t, err)
	out := string(got)

	// goose's splitter mangles dollar-quoted function bodies unless they are fenced.
	require.Contains(t, out, "-- +goose StatementBegin")
	require.Contains(t, out, "-- +goose StatementEnd")
	assert.Equal(t, 1, strings.Count(out, "-- +goose StatementBegin"),
		"only the function body needs fencing")
	assert.True(t, strings.HasPrefix(out, "-- Code generated by tools/logpollerschema. DO NOT EDIT."),
		"generated file must carry the header")
	assert.Contains(t, out, "FROZEN ONCE APPLIED",
		"the header must warn that regenerating cannot reach a deployed database")
}

func TestGenerate_SequenceCreatedBeforeUse(t *testing.T) {
	t.Parallel()

	got, err := logpollerschema.Generate([]byte(sampleDump), testRef)
	require.NoError(t, err)
	out := string(got)

	create := strings.Index(out, "CREATE SEQUENCE evm.evm_log_poller_filters_id_seq")
	table := strings.Index(out, "CREATE TABLE evm.log_poller_filters")
	require.NotEqual(t, -1, create)
	require.NotEqual(t, -1, table)
	// goose applies top to bottom, so dependency order in the dump must be preserved.
	assert.Greater(t, create, table, "pg_dump order must be preserved")
}

func TestGenerate_RejectsInputWithoutSchema(t *testing.T) {
	t.Parallel()

	_, err := logpollerschema.Generate([]byte("CREATE TABLE public.jobs (id bigint);\n"), testRef)
	require.Error(t, err, "a dump with no evm objects must not yield a partial schema")
}

// TestMain_RefusesToOverwriteFrozenMigration covers the guard that stops someone
// regenerating the initial migration after it has shipped. A later migration is the
// signal that it has: regenerating then changes what fresh installs get without
// touching any deployed database, and the two silently diverge.
func TestMain_RefusesToOverwriteFrozenMigration(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	initial := filepath.Join(dir, "00001_evm_logpoller_schema.sql")
	require.NoError(t, os.WriteFile(initial, []byte("-- shipped\n"), 0o600))

	// No later migration yet: regenerating is still safe (pre-deployment).
	require.NoError(t, logpollerschema.CheckNotFrozen(initial))

	// A delta migration appears -- the initial one is now frozen.
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "00002_add_column.sql"), []byte("-- delta\n"), 0o600))

	err := logpollerschema.CheckNotFrozen(initial)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "00002_add_column.sql",
		"the error should name what froze it")
}
