// Package logpollerschema turns a pg_dump of the Chainlink node's `evm` schema (from
// derive.sh) into the goose migration CCV ships for the standalone verifier.
package logpollerschema

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"
)

// header returns the preamble for the generated DDL. chainlinkRef is stamped in because
// `chainlink` is not a CCV dependency -- there is no go.mod entry recording which node
// tree this came from, so this line is the only provenance.
func header(chainlinkRef string) string {
	return `-- Code generated by tools/logpollerschema. DO NOT EDIT.
--
-- The end-state ` + "`evm`" + ` LogPoller schema, derived from the Chainlink node's own migrator
-- (see tools/logpollerschema/derive.sh) rather than replayed from its migration files. Replay is
-- not possible: the node's set relocates tables between schemas, declares a foreign key to
-- a table a later migration drops, and recreates a trigger a later migration removes.
--
-- Derived from chainlink ` + chainlinkRef + `
--
-- Applies only to the standalone verifier. In-node, the node's migrator owns this schema.
--
-- FROZEN ONCE APPLIED. goose records this migration's version the first time it runs and
-- never re-runs it, so editing or regenerating this file cannot change a database that
-- already has it. Fresh installs would get something different from upgraded ones, with
-- nothing to catch the divergence. Schema changes belong in a NEW numbered migration
-- containing only the delta, hand-written and reviewed. The generator refuses to
-- overwrite this file once a later migration exists.
--
-- Drift between this schema and the chainlink-evm ORM that CCV pins is caught by
-- ` + "`just logpoller-orm-contract`" + `, which runs the pinned ORM's own test suite against a
-- database built from these migrations.

-- +goose Up
`
}

// keep matches the objects the LogPoller ORM touches; everything else in the node's `evm`
// schema belongs to the node.
//
// The sequence is listed separately because its name doubles the prefix
// (`evm.evm_log_poller_filters_id_seq`), so a `\bevm\.log_poller_filters\b` pattern misses
// it -- while the statements referencing it match, producing a file that uses a sequence
// it never creates.
var keep = regexp.MustCompile(
	`\b(evm\.evm_log_poller_filters_id_seq|evm\.logs|evm\.log_poller_blocks|evm\.log_poller_filters|f_log_poller_filter_hash)\b`,
)

var stmtSep = regexp.MustCompile(`\n\n+`)

// Generate filters a pg_dump of the `evm` schema down to the LogPoller objects and wraps
// the result as a goose migration. There is no Down: CCV only runs goose.Up.
func Generate(dump []byte, chainlinkRef string) ([]byte, error) {
	if strings.TrimSpace(chainlinkRef) == "" {
		return nil, fmt.Errorf("chainlink ref is required; the generated schema must record what it was derived from")
	}

	var kept []string
	for _, raw := range stmtSep.Split(string(dump), -1) {
		stmt := strings.TrimSpace(raw)
		if !include(stmt) {
			continue
		}
		// Dollar-quoted bodies must be fenced or goose's splitter mangles them.
		if strings.Contains(stmt, "$_$") || strings.Contains(stmt, "$$") {
			stmt = "-- +goose StatementBegin\n" + stmt + "\n-- +goose StatementEnd"
		}
		kept = append(kept, stmt)
	}

	if len(kept) == 0 {
		return nil, fmt.Errorf("no statements matched; input does not look like a pg_dump of the evm schema")
	}
	if !bytes.Contains([]byte(strings.Join(kept, "\n")), []byte("CREATE SCHEMA evm")) {
		return nil, fmt.Errorf("input is missing CREATE SCHEMA evm; refusing to emit a partial schema")
	}

	var buf bytes.Buffer
	_, _ = buf.WriteString(header(chainlinkRef))
	for _, stmt := range kept {
		_, _ = buf.WriteString("\n")
		_, _ = buf.WriteString(stmt)
		_, _ = buf.WriteString("\n")
	}
	return buf.Bytes(), nil
}

// include reports whether a pg_dump statement belongs in the generated migration.
func include(stmt string) bool {
	if stmt == "" {
		return false
	}
	// Standalone single-line comment; multi-line blocks belong to the statement below.
	if strings.HasPrefix(stmt, "--") && !strings.Contains(stmt, "\n") {
		return false
	}
	if strings.HasPrefix(stmt, "SET ") || strings.HasPrefix(stmt, "SELECT pg_catalog") {
		return false
	}
	return strings.Contains(stmt, "CREATE SCHEMA evm") || keep.MatchString(stmt)
}
