package model

// GeneratedConfig contains auto-generated deployment configuration.
// This is typically generated by tooling and loaded from a separate file.
type GeneratedConfig struct {
	Committee *Committee `toml:"committee"`
}

// MergeGeneratedConfig merges the generated configuration into the main configuration.
// The generated config takes precedence, overwriting any existing Committee configuration.
func (c *AggregatorConfig) MergeGeneratedConfig(generated *GeneratedConfig) {
	if generated == nil {
		return
	}
	if generated.Committee != nil {
		c.Committee = generated.Committee
	}
}
