// Code generated by github.com/smartcontractkit/chainlink-ccv/tools/configdoc, DO NOT EDIT.

package lombard

import "github.com/smartcontractkit/chainlink-common/x/config/commentparsing"

func (LombardConfig) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"AttestationAPIInterval": {Comment: "AttestationAPIInterval defines the rate in requests per second that the attestation API can be called.\nDefault set according to the APIs documentated 10 requests per second rate limit."},
		"AttestationAPITimeout":  {Comment: "AttestationAPITimeout defines the timeout for the attestation API."},
		"VerifierResolvers":      {Comment: "VerifierResolvers is a map of chain selectors to verifier resolver addresses. It's only used for TOML marshall/unmarshall and then\nfinal values, properly cast to domain values are stored in ParsedVerifierResolvers"},
		"VerifierVersion":        {Comment: "VerifierVersion is the parsed verifier version of the Lombard verifier contract.\nDefaults to DefaultVerifierVersion if not specified."},
	}
}
