package configdoc

import (
	"bytes"
	"fmt"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/BurntSushi/toml"
)

// Generator renders documentation targets to commented TOML. ModuleRoot is the
// filesystem path of the module root; ModulePath is its import path.
type Generator struct {
	ModuleRoot string
	ModulePath string
}

// Render produces the documented TOML for one target: it TOML-encodes the
// target's fully-populated instance (the encoder does all structure/value
// walking), loads the doc comments for the packages the instance's structs live
// in, and injects those comments into the encoded output.
func (g *Generator) Render(t Target) (string, error) {
	inst := t.New()

	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(inst); err != nil {
		return "", fmt.Errorf("%s: encoding: %w", t.Name, err)
	}

	comments, err := LoadComments(g.packageDirs(inst))
	if err != nil {
		return "", fmt.Errorf("%s: loading comments: %w", t.Name, err)
	}

	body, err := InjectComments(buf.String(), reflect.TypeOf(inst), comments)
	if err != nil {
		return "", fmt.Errorf("%s: %w", t.Name, err)
	}
	return g.header(t) + body, nil
}

func (g *Generator) header(t Target) string {
	kind := "configuration"
	if t.Kind == KindSecrets {
		kind = "secrets"
	}
	return fmt.Sprintf(
		"# Code generated by tools/configdoc. DO NOT EDIT.\n"+
			"# %s %s reference. Values shown are defaults or illustrative examples.\n\n",
		titleCase(t.Name), kind,
	)
}

// packageDirs maps each package contributing a field on inst to its source
// directory, so LoadComments indexes exactly the needed packages.
func (g *Generator) packageDirs(inst any) map[string]string {
	dirs := map[string]string{}
	for pkg := range collectPackages(reflect.TypeOf(inst)) {
		rel := strings.TrimPrefix(strings.TrimPrefix(pkg, g.ModulePath), "/")
		dirs[pkg] = filepath.Join(g.ModuleRoot, filepath.FromSlash(rel))
	}
	return dirs
}

// collectPackages returns the set of package import paths of every struct type
// reachable through the fields of t (following embeds, nested structs, and
// struct-valued maps/slices).
func collectPackages(t reflect.Type) map[string]bool {
	out := map[string]bool{}
	visited := map[reflect.Type]bool{}
	var walk func(reflect.Type)
	walk = func(t reflect.Type) {
		t = deref(t)
		if t.Kind() != reflect.Struct || visited[t] {
			return
		}
		visited[t] = true
		if t.PkgPath() != "" {
			out[t.PkgPath()] = true
		}
		for _, f := range reflect.VisibleFields(t) {
			if !f.IsExported() {
				continue
			}
			ft := deref(f.Type)
			switch ft.Kind() {
			case reflect.Struct:
				walk(ft)
			case reflect.Slice, reflect.Array, reflect.Map:
				if ft.Elem().Kind() == reflect.Struct {
					walk(ft.Elem())
				}
			}
		}
	}
	walk(t)
	return out
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
