root = ".."

[build]
cmd = "go build -o /tmp/executor /app/cmd/executor"
bin = "/tmp/executor"
include_dir = ["app"]
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "testdata", ".git"]
