indexer_address="http://indexer:8100"
source_polling_interval="5s"
source_backoff_duration="15s"
startup_lookback_window="1h"
indexer_query_limit=20
pyroscope_url="http://pyroscope:4040"
executor_pool=["cl_node_executor_a"]
executor_id="cl_node_executor_a"
execution_interval="15s"
min_wait="3s"
ccv_info_cache_expiry="5m"

[offramp_addresses]
    100 = "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
    101 = "0x8f86403A4DE0BB5791fa46B8e795C547942fE4Cf"
    102 = "0x36b58F5C1969B7b6591D752ea6F5486D069010AB"

[blockchain_infos]
    [blockchain_infos.100]
        ChainID = "1337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-shared"
        [[blockchain_infos.100.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8545"
            InternalHTTPUrl = "http://blockchain-shared:8545"
            ExternalWSUrl = "ws://host.docker.internal:8545"
            InternalWSUrl = "ws://blockchain-shared:8545"
    [blockchain_infos.101]
        ChainID = "1337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-shared"
        [[blockchain_infos.101.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8545"
            InternalHTTPUrl = "http://blockchain-shared:8545"
            ExternalWSUrl = "ws://host.docker.internal:8545"
            InternalWSUrl = "ws://blockchain-shared:8545"
    [blockchain_infos.102]
        ChainID = "1337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-shared"
        [[blockchain_infos.102.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8545"
            InternalHTTPUrl = "http://blockchain-shared:8545"
            ExternalWSUrl = "ws://host.docker.internal:8545"
            InternalWSUrl = "ws://blockchain-shared:8545"

[Monitoring]
Enabled = true
Type = "beholder"
[Monitoring.Beholder]
InsecureConnection = true
CACertFile = ""
OtelExporterGRPCEndpoint = ""
OtelExporterHTTPEndpoint = "otel-collector:4318"
LogStreamingEnabled = true
MetricReaderInterval = 5
TraceSampleRatio = 1.0
TraceBatchTimeout = 10
