indexer_address="http://indexer:8100"
source_polling_interval="5s"
source_backoff_duration="15s"
startup_lookback_window="1h"
indexer_query_limit=20
pyroscope_url="http://pyroscope:4040"
executor_pool=["cl_node_executor_a"]
executor_id="cl_node_executor_a"
execution_interval="15s"
min_wait="3s"
ccv_info_cache_expiry="5m"

[offramp_addresses]
    3379446385462418246 = "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
    12922642891491394802 = "0x8f86403A4DE0BB5791fa46B8e795C547942fE4Cf"
    4793464827907405086 = "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"

[blockchain_infos]
    [blockchain_infos.3379446385462418246]
        ChainID = "1337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-shared"
        [[blockchain_infos.3379446385462418246.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8545"
            InternalHTTPUrl = "http://blockchain-shared:8545"
            ExternalWSUrl = "ws://host.docker.internal:8545"
            InternalWSUrl = "ws://blockchain-shared:8545"
    [blockchain_infos.12922642891491394802]
        ChainID = "1337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-shared"
        [[blockchain_infos.12922642891491394802.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8545"
            InternalHTTPUrl = "http://blockchain-shared:8545"
            ExternalWSUrl = "ws://host.docker.internal:8545"
            InternalWSUrl = "ws://blockchain-shared:8545"
    [blockchain_infos.4793464827907405086]
        ChainID = "2337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-shared-2"
        [[blockchain_infos.4793464827907405086.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8555"
            InternalHTTPUrl = "http://blockchain-shared-2:8555"
            ExternalWSUrl = "ws://host.docker.internal:8555"
            InternalWSUrl = "ws://blockchain-shared-2:8555"

[Monitoring]
Enabled = true
Type = "beholder"
[Monitoring.Beholder]
InsecureConnection = true
CACertFile = ""
OtelExporterGRPCEndpoint = ""
OtelExporterHTTPEndpoint = "otel-collector:4318"
LogStreamingEnabled = true
MetricReaderInterval = 5
TraceSampleRatio = 1.0
TraceBatchTimeout = 10
