indexer_address="http://indexer:8100"
source_polling_interval="5s"
source_backoff_duration="15s"
startup_lookback_window="1h"
indexer_query_limit=20
pyroscope_url="http://pyroscope:4040"
executor_pool=["cl_node_executor_a", "cl_node_executor_b"]
executor_id="cl_node_executor_a"
execution_interval="15s"
min_wait="3s"

[offramp_addresses]
    3379446385462418246 = "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
    12922642891491394802 = "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
    4793464827907405086 = "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"

[blockchain_infos]
    [blockchain_infos.3379446385462418246]
        ChainID = "1337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-src"
        [[blockchain_infos.3379446385462418246.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8545"
            InternalHTTPUrl = "http://blockchain-src:8545"
            ExternalWSUrl = "ws://host.docker.internal:8545"
            InternalWSUrl = "ws://blockchain-src:8545"
    [blockchain_infos.12922642891491394802]
        ChainID = "2337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-dst"
        [[blockchain_infos.12922642891491394802.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8555"
            InternalHTTPUrl = "http://blockchain-dst:8555"
            ExternalWSUrl = "ws://host.docker.internal:8555"
            InternalWSUrl = "ws://blockchain-dst:8555"
    [blockchain_infos.4793464827907405086]
        ChainID = "3337"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "blockchain-3rd"
        [[blockchain_infos.4793464827907405086.Nodes]]
            ExternalHTTPUrl = "http://host.docker.internal:8565"
            InternalHTTPUrl = "http://blockchain-3rd:8565"
            ExternalWSUrl = "ws://host.docker.internal:8565"
            InternalWSUrl = "ws://blockchain-3rd:8565"
