// Code generated by mockery v2.53.5. DO NOT EDIT.

package aggregation_mocks

import (
	context "context"

	model "github.com/smartcontractkit/chainlink-ccv/aggregator/pkg/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCommitVerificationStore is an autogenerated mock type for the CommitVerificationStore type
type MockCommitVerificationStore struct {
	mock.Mock
}

type MockCommitVerificationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitVerificationStore) EXPECT() *MockCommitVerificationStore_Expecter {
	return &MockCommitVerificationStore_Expecter{mock: &_m.Mock}
}

// GetCommitVerification provides a mock function with given fields: ctx, id
func (_m *MockCommitVerificationStore) GetCommitVerification(ctx context.Context, id model.CommitVerificationRecordIdentifier) (*model.CommitVerificationRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCommitVerification")
	}

	var r0 *model.CommitVerificationRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CommitVerificationRecordIdentifier) (*model.CommitVerificationRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CommitVerificationRecordIdentifier) *model.CommitVerificationRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CommitVerificationRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CommitVerificationRecordIdentifier) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommitVerificationStore_GetCommitVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommitVerification'
type MockCommitVerificationStore_GetCommitVerification_Call struct {
	*mock.Call
}

// GetCommitVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - id model.CommitVerificationRecordIdentifier
func (_e *MockCommitVerificationStore_Expecter) GetCommitVerification(ctx interface{}, id interface{}) *MockCommitVerificationStore_GetCommitVerification_Call {
	return &MockCommitVerificationStore_GetCommitVerification_Call{Call: _e.mock.On("GetCommitVerification", ctx, id)}
}

func (_c *MockCommitVerificationStore_GetCommitVerification_Call) Run(run func(ctx context.Context, id model.CommitVerificationRecordIdentifier)) *MockCommitVerificationStore_GetCommitVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CommitVerificationRecordIdentifier))
	})
	return _c
}

func (_c *MockCommitVerificationStore_GetCommitVerification_Call) Return(_a0 *model.CommitVerificationRecord, _a1 error) *MockCommitVerificationStore_GetCommitVerification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommitVerificationStore_GetCommitVerification_Call) RunAndReturn(run func(context.Context, model.CommitVerificationRecordIdentifier) (*model.CommitVerificationRecord, error)) *MockCommitVerificationStore_GetCommitVerification_Call {
	_c.Call.Return(run)
	return _c
}

// ListCommitVerificationByAggregationKey provides a mock function with given fields: ctx, messageID, aggregationKey
func (_m *MockCommitVerificationStore) ListCommitVerificationByAggregationKey(ctx context.Context, messageID []byte, aggregationKey string) ([]*model.CommitVerificationRecord, error) {
	ret := _m.Called(ctx, messageID, aggregationKey)

	if len(ret) == 0 {
		panic("no return value specified for ListCommitVerificationByAggregationKey")
	}

	var r0 []*model.CommitVerificationRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) ([]*model.CommitVerificationRecord, error)); ok {
		return rf(ctx, messageID, aggregationKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) []*model.CommitVerificationRecord); ok {
		r0 = rf(ctx, messageID, aggregationKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.CommitVerificationRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string) error); ok {
		r1 = rf(ctx, messageID, aggregationKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCommitVerificationByAggregationKey'
type MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call struct {
	*mock.Call
}

// ListCommitVerificationByAggregationKey is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID []byte
//   - aggregationKey string
func (_e *MockCommitVerificationStore_Expecter) ListCommitVerificationByAggregationKey(ctx interface{}, messageID interface{}, aggregationKey interface{}) *MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call {
	return &MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call{Call: _e.mock.On("ListCommitVerificationByAggregationKey", ctx, messageID, aggregationKey)}
}

func (_c *MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call) Run(run func(ctx context.Context, messageID []byte, aggregationKey string)) *MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string))
	})
	return _c
}

func (_c *MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call) Return(_a0 []*model.CommitVerificationRecord, _a1 error) *MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call) RunAndReturn(run func(context.Context, []byte, string) ([]*model.CommitVerificationRecord, error)) *MockCommitVerificationStore_ListCommitVerificationByAggregationKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrphanedKeys provides a mock function with given fields: ctx, newerThan
func (_m *MockCommitVerificationStore) ListOrphanedKeys(ctx context.Context, newerThan time.Time) (<-chan model.OrphanedKey, <-chan error) {
	ret := _m.Called(ctx, newerThan)

	if len(ret) == 0 {
		panic("no return value specified for ListOrphanedKeys")
	}

	var r0 <-chan model.OrphanedKey
	var r1 <-chan error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (<-chan model.OrphanedKey, <-chan error)); ok {
		return rf(ctx, newerThan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) <-chan model.OrphanedKey); ok {
		r0 = rf(ctx, newerThan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.OrphanedKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) <-chan error); ok {
		r1 = rf(ctx, newerThan)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	return r0, r1
}

// MockCommitVerificationStore_ListOrphanedKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrphanedKeys'
type MockCommitVerificationStore_ListOrphanedKeys_Call struct {
	*mock.Call
}

// ListOrphanedKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - newerThan time.Time
func (_e *MockCommitVerificationStore_Expecter) ListOrphanedKeys(ctx interface{}, newerThan interface{}) *MockCommitVerificationStore_ListOrphanedKeys_Call {
	return &MockCommitVerificationStore_ListOrphanedKeys_Call{Call: _e.mock.On("ListOrphanedKeys", ctx, newerThan)}
}

func (_c *MockCommitVerificationStore_ListOrphanedKeys_Call) Run(run func(ctx context.Context, newerThan time.Time)) *MockCommitVerificationStore_ListOrphanedKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockCommitVerificationStore_ListOrphanedKeys_Call) Return(_a0 <-chan model.OrphanedKey, _a1 <-chan error) *MockCommitVerificationStore_ListOrphanedKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommitVerificationStore_ListOrphanedKeys_Call) RunAndReturn(run func(context.Context, time.Time) (<-chan model.OrphanedKey, <-chan error)) *MockCommitVerificationStore_ListOrphanedKeys_Call {
	_c.Call.Return(run)
	return _c
}

// OrphanedKeyStats provides a mock function with given fields: ctx, cutoff
func (_m *MockCommitVerificationStore) OrphanedKeyStats(ctx context.Context, cutoff time.Time) (*model.OrphanStats, error) {
	ret := _m.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for OrphanedKeyStats")
	}

	var r0 *model.OrphanStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*model.OrphanStats, error)); ok {
		return rf(ctx, cutoff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *model.OrphanStats); ok {
		r0 = rf(ctx, cutoff)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrphanStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommitVerificationStore_OrphanedKeyStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrphanedKeyStats'
type MockCommitVerificationStore_OrphanedKeyStats_Call struct {
	*mock.Call
}

// OrphanedKeyStats is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *MockCommitVerificationStore_Expecter) OrphanedKeyStats(ctx interface{}, cutoff interface{}) *MockCommitVerificationStore_OrphanedKeyStats_Call {
	return &MockCommitVerificationStore_OrphanedKeyStats_Call{Call: _e.mock.On("OrphanedKeyStats", ctx, cutoff)}
}

func (_c *MockCommitVerificationStore_OrphanedKeyStats_Call) Run(run func(ctx context.Context, cutoff time.Time)) *MockCommitVerificationStore_OrphanedKeyStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockCommitVerificationStore_OrphanedKeyStats_Call) Return(_a0 *model.OrphanStats, _a1 error) *MockCommitVerificationStore_OrphanedKeyStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommitVerificationStore_OrphanedKeyStats_Call) RunAndReturn(run func(context.Context, time.Time) (*model.OrphanStats, error)) *MockCommitVerificationStore_OrphanedKeyStats_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCommitVerification provides a mock function with given fields: ctx, record, aggregationKey
func (_m *MockCommitVerificationStore) SaveCommitVerification(ctx context.Context, record *model.CommitVerificationRecord, aggregationKey string) error {
	ret := _m.Called(ctx, record, aggregationKey)

	if len(ret) == 0 {
		panic("no return value specified for SaveCommitVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CommitVerificationRecord, string) error); ok {
		r0 = rf(ctx, record, aggregationKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommitVerificationStore_SaveCommitVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCommitVerification'
type MockCommitVerificationStore_SaveCommitVerification_Call struct {
	*mock.Call
}

// SaveCommitVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - record *model.CommitVerificationRecord
//   - aggregationKey string
func (_e *MockCommitVerificationStore_Expecter) SaveCommitVerification(ctx interface{}, record interface{}, aggregationKey interface{}) *MockCommitVerificationStore_SaveCommitVerification_Call {
	return &MockCommitVerificationStore_SaveCommitVerification_Call{Call: _e.mock.On("SaveCommitVerification", ctx, record, aggregationKey)}
}

func (_c *MockCommitVerificationStore_SaveCommitVerification_Call) Run(run func(ctx context.Context, record *model.CommitVerificationRecord, aggregationKey string)) *MockCommitVerificationStore_SaveCommitVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CommitVerificationRecord), args[2].(string))
	})
	return _c
}

func (_c *MockCommitVerificationStore_SaveCommitVerification_Call) Return(_a0 error) *MockCommitVerificationStore_SaveCommitVerification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommitVerificationStore_SaveCommitVerification_Call) RunAndReturn(run func(context.Context, *model.CommitVerificationRecord, string) error) *MockCommitVerificationStore_SaveCommitVerification_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommitVerificationStore creates a new instance of MockCommitVerificationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitVerificationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitVerificationStore {
	mock := &MockCommitVerificationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
