[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.94.1"

[workspace.dependencies]
alloy = { version = "2", features = ["full"] }
alloy-primitives = "1"
async-trait = "0.1"
thiserror = "2"
tracing = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
hex-literal = "0.4"
