// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	jobqueue "github.com/smartcontractkit/chainlink-ccv/cli/jobqueue"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// ListFailed provides a mock function with given fields: ctx, queues, ownerID, limit
func (_m *MockStore) ListFailed(ctx context.Context, queues []jobqueue.QueueType, ownerID string, limit int) ([]jobqueue.ArchivedJob, error) {
	ret := _m.Called(ctx, queues, ownerID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListFailed")
	}

	var r0 []jobqueue.ArchivedJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []jobqueue.QueueType, string, int) ([]jobqueue.ArchivedJob, error)); ok {
		return rf(ctx, queues, ownerID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []jobqueue.QueueType, string, int) []jobqueue.ArchivedJob); ok {
		r0 = rf(ctx, queues, ownerID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jobqueue.ArchivedJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []jobqueue.QueueType, string, int) error); ok {
		r1 = rf(ctx, queues, ownerID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFailed'
type MockStore_ListFailed_Call struct {
	*mock.Call
}

// ListFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - queues []jobqueue.QueueType
//   - ownerID string
//   - limit int
func (_e *MockStore_Expecter) ListFailed(ctx interface{}, queues interface{}, ownerID interface{}, limit interface{}) *MockStore_ListFailed_Call {
	return &MockStore_ListFailed_Call{Call: _e.mock.On("ListFailed", ctx, queues, ownerID, limit)}
}

func (_c *MockStore_ListFailed_Call) Run(run func(ctx context.Context, queues []jobqueue.QueueType, ownerID string, limit int)) *MockStore_ListFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]jobqueue.QueueType), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockStore_ListFailed_Call) Return(_a0 []jobqueue.ArchivedJob, _a1 error) *MockStore_ListFailed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListFailed_Call) RunAndReturn(run func(context.Context, []jobqueue.QueueType, string, int) ([]jobqueue.ArchivedJob, error)) *MockStore_ListFailed_Call {
	_c.Call.Return(run)
	return _c
}

// RescheduleByJobID provides a mock function with given fields: ctx, queue, ownerID, jobID, retryDuration
func (_m *MockStore) RescheduleByJobID(ctx context.Context, queue jobqueue.QueueType, ownerID string, jobID string, retryDuration time.Duration) error {
	ret := _m.Called(ctx, queue, ownerID, jobID, retryDuration)

	if len(ret) == 0 {
		panic("no return value specified for RescheduleByJobID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, jobqueue.QueueType, string, string, time.Duration) error); ok {
		r0 = rf(ctx, queue, ownerID, jobID, retryDuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_RescheduleByJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RescheduleByJobID'
type MockStore_RescheduleByJobID_Call struct {
	*mock.Call
}

// RescheduleByJobID is a helper method to define mock.On call
//   - ctx context.Context
//   - queue jobqueue.QueueType
//   - ownerID string
//   - jobID string
//   - retryDuration time.Duration
func (_e *MockStore_Expecter) RescheduleByJobID(ctx interface{}, queue interface{}, ownerID interface{}, jobID interface{}, retryDuration interface{}) *MockStore_RescheduleByJobID_Call {
	return &MockStore_RescheduleByJobID_Call{Call: _e.mock.On("RescheduleByJobID", ctx, queue, ownerID, jobID, retryDuration)}
}

func (_c *MockStore_RescheduleByJobID_Call) Run(run func(ctx context.Context, queue jobqueue.QueueType, ownerID string, jobID string, retryDuration time.Duration)) *MockStore_RescheduleByJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(jobqueue.QueueType), args[2].(string), args[3].(string), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockStore_RescheduleByJobID_Call) Return(_a0 error) *MockStore_RescheduleByJobID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_RescheduleByJobID_Call) RunAndReturn(run func(context.Context, jobqueue.QueueType, string, string, time.Duration) error) *MockStore_RescheduleByJobID_Call {
	_c.Call.Return(run)
	return _c
}

// RescheduleByMessageID provides a mock function with given fields: ctx, queue, ownerID, messageID, retryDuration
func (_m *MockStore) RescheduleByMessageID(ctx context.Context, queue jobqueue.QueueType, ownerID string, messageID []byte, retryDuration time.Duration) error {
	ret := _m.Called(ctx, queue, ownerID, messageID, retryDuration)

	if len(ret) == 0 {
		panic("no return value specified for RescheduleByMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, jobqueue.QueueType, string, []byte, time.Duration) error); ok {
		r0 = rf(ctx, queue, ownerID, messageID, retryDuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_RescheduleByMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RescheduleByMessageID'
type MockStore_RescheduleByMessageID_Call struct {
	*mock.Call
}

// RescheduleByMessageID is a helper method to define mock.On call
//   - ctx context.Context
//   - queue jobqueue.QueueType
//   - ownerID string
//   - messageID []byte
//   - retryDuration time.Duration
func (_e *MockStore_Expecter) RescheduleByMessageID(ctx interface{}, queue interface{}, ownerID interface{}, messageID interface{}, retryDuration interface{}) *MockStore_RescheduleByMessageID_Call {
	return &MockStore_RescheduleByMessageID_Call{Call: _e.mock.On("RescheduleByMessageID", ctx, queue, ownerID, messageID, retryDuration)}
}

func (_c *MockStore_RescheduleByMessageID_Call) Run(run func(ctx context.Context, queue jobqueue.QueueType, ownerID string, messageID []byte, retryDuration time.Duration)) *MockStore_RescheduleByMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(jobqueue.QueueType), args[2].(string), args[3].([]byte), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockStore_RescheduleByMessageID_Call) Return(_a0 error) *MockStore_RescheduleByMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_RescheduleByMessageID_Call) RunAndReturn(run func(context.Context, jobqueue.QueueType, string, []byte, time.Duration) error) *MockStore_RescheduleByMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
