with-expecter: true

dir: ./internal/executor_mocks
outpkg: executor_mocks

packages:
    github.com/smartcontractkit/chainlink-ccv/executor:
        interfaces:
            CCVResultStreamer:
            Executor:
            ContractTransmitter:
            LeaderElector:
            DestinationReader:
    github.com/smartcontractkit/chainlink-ccv/protocol:
        interfaces:
            OffchainStorageReader:
