with-expecter: true

dir: ./internal/executor_mocks
outpkg: executor_mocks

packages:
    github.com/smartcontractkit/chainlink-ccv/executor:
        interfaces:
            CCVResultStreamer:
    github.com/smartcontractkit/chainlink-ccv/executor/pkg/executor:
        interfaces:
            Executor:
    github.com/smartcontractkit/chainlink-ccv/executor/pkg/contracttransmitter:
        interfaces:
            ContractTransmitter:
    github.com/smartcontractkit/chainlink-ccv/executor/pkg/leaderelector:
        interfaces:
            LeaderElector:
    github.com/smartcontractkit/chainlink-ccv/protocol/pkg/types:
        interfaces:
            OffchainStorageReader:
