root = ".."

[build]
cmd = "go build -o ./tmp/executor cmd/main.go"
bin = "tmp/executor"
include_dir = ["app", "protocol"]
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "testdata", ".git"]