root = ".."

[build]
cmd = "go build -o ./tmp/executor ../common/cmd/executor.go"
bin = "tmp/executor"
include_dir = ["app", "protocol", "common"]
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "testdata", ".git"]