// Code generated by github.com/smartcontractkit/chainlink-ccv/tools/configdoc, DO NOT EDIT.

package executor

import "github.com/smartcontractkit/chainlink-common/x/config/commentparsing"

func (ChainConfiguration) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"DefaultExecutorAddress": {Comment: "DefaultExecutorAddress is the address of the default executor to check against the message receipts."},
		"DestinationChainConfig": {Comment: "DestinationChainConfig holds the off-ramp and RMN addresses. It is embedded so that the\nTOML field paths (off_ramp_address, rmn_address) are identical to what the chainaccess\nRegistry reads via ExecutorConfig, allowing both to overlay the same config file. The\nrmn_address field is deprecated (derived on-chain) but still decoded for back-compat."},
		"ExecutionInterval":      {Comment: "ExecutionInterval is how long each executor has to process a message before the next executor in the cluster takes over."},
		"ExecutorPool":           {Comment: "ExecutorPool is the list of executor IDs used for turn taking. This executor's ID must be in the list."},
	}
}

func (Configuration) DocComments() map[string]commentparsing.FieldDoc {
	return map[string]commentparsing.FieldDoc{
		"BackoffDuration":           {Comment: "BackoffDuration is the duration to back off after a failed request to the Indexer.\nDefaults to 15 seconds.\nIt controls Indexer retries only; NTP uses a fixed 2-second backoff base."},
		"ChainConfiguration":        {Comment: "ChainConfiguration is a map of chain selector to chain configuration.\nThis is used to configure the chain-specific configuration for each chain such as addresses, executor pool, and execution interval."},
		"DataNotReadyRetryInterval": {Comment: "DataNotReadyRetryInterval is the base delay between retries when verifier data is not yet available.\nDefaults to 1 second. Exponential backoff applies up to the executor stagger interval."},
		"ExecutorID":                {Comment: "ExecutorID is the ID of this executor. This executorID should be present in the executor pool."},
		"HTTPListenPort":            {Comment: "HTTPListenPort is the port the executor's own HTTP server (/health) listens on.\nDefaults to 8101. Inert in CL mode, which serves its own API.\nOmitted from marshaled job specs when unset so CL-mode specs are unchanged."},
		"IndexerAddress":            {Comment: "IndexerAddress is the list of indexer URLs to receive messages + verifications from.\nThe executor will use these for failover if one indexer becomes unavailable."},
		"IndexerQueryLimit":         {Comment: "IndexerQueryLimit is the maximum number of messages to query from the Indexer at once.\nDefaults to 100."},
		"LookbackWindow":            {Comment: "LookbackWindow is the window of time to look back for new messages when an Executor first starts up.\nDefaults to 1 hour."},
		"MaxRetryDuration":          {Comment: "MaxRetryDuration is the maximum duration the executor cluster will retry a message before giving up.\nDefaults to 8 hours."},
		"Monitoring":                {Comment: "Monitoring is deprecated and ignored. Standalone monitoring comes from the bootstrap\nconfig's [Monitoring] section and CL-mode monitoring from the node; this section has no\nconsumer in either mode. It is retained so older job specs still decode, and it is\nintentionally not validated."},
		"NtpServer":                 {Comment: "NtpServer is the NTP server to use for time synchronization.\nDefaults to time.google.com\nNTP retries are independent of source_backoff_duration."},
		"PyroscopeURL":              {Comment: "PyroscopeURL is the URL of the Pyroscope server to send metrics to."},
		"ReaderCacheExpiry":         {Comment: "ReaderCacheExpiry is the duration for the curse checker cache (RMN cursed state per chain).\nDefaults to 5 minutes."},
		"WorkerCount":               {Comment: "WorkerCount is the number of concurrent workers processing messages.\nDefaults to 100."},
	}
}
