FROM golang:1.24.6-alpine
RUN go install github.com/air-verse/air@v1.62.0
WORKDIR /
COPY protocol/ ./protocol/
COPY common/ ./common/
WORKDIR /app
COPY ../common/go.mod ../common/go.sum ./
WORKDIR /app
RUN go mod download
COPY executor/air.toml ./
CMD ["air", "-c", "air.toml"]