indexer_address="http://chainlink-ccv-indexer:8100"
private_key="example"
source_polling_interval="5s"
source_backoff_duration="15s"
startup_lookback_window="1h"
indexer_query_limit=20
pyroscope_url="http://pyroscope:4040"
[blockchain_infos]
    [blockchain_infos.14767482510784806043]
        ChainID = "43113"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "avax-fuji"
        OfframpAddress ="0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
        [[blockchain_infos.14767482510784806043.Nodes]]
            ExternalHTTPUrl = "https://rpcs.cldev.sh/avalanche/fuji"
            InternalHTTPUrl = "https://rpcs.cldev.sh/avalanche/fuji"
            ExternalWSUrl = "wss://rpcs.cldev.sh/avalanche/fuji"
            InternalWSUrl = "wss://rpcs.cldev.sh/avalanche/fuji"
    [blockchain_infos.4905564228793744293]
        ChainID = "4002"
        Type = "anvil"
        Family = "evm"
        UniqueChainName = "sonic-blaze"
        OfframpAddress ="0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
        [[blockchain_infos.4905564228793744293.Nodes]]
            ExternalHTTPUrl = "https://rpcs.cldev.sh/fantom/testnet"
            InternalHTTPUrl = "https://rpcs.cldev.sh/fantom/testnet"
            ExternalWSUrl = "wss://rpcs.cldev.sh/fantom/testnet"
            InternalWSUrl = "wss://rpcs.cldev.sh/fantom/testnet"