indexer_address="indexer:50051"
private_key="ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
source_polling_interval="5s"
source_backoff_duration="15s"
[blockchain_infos]
    [blockchain_infos.3379446385462418246]
        ChainID = "1337"
        Type = "anvil"
        Family = "evm"
        ContainerName = "blockchain-src"
        OfframpRouter ="0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
        [[blockchain_infos.3379446385462418246.Nodes]]
            ExternalHTTPUrl = "http://127.0.0.1:8545"
            InternalHTTPUrl = "http://blockchain-src:8545"
            ExternalWSUrl = "ws://127.0.0.1:8545"
            InternalWSUrl = "ws://blockchain-src:8545"
    [blockchain_infos.12922642891491394802]
        ChainID = "2337"
        Type = "anvil"
        Family = "evm"
        OfframpRouter ="0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
        ContainerName = "blockchain-dst"
        [[blockchain_infos.12922642891491394802.Nodes]]
            ExternalHTTPUrl = "http://127.0.0.1:8555"
            InternalHTTPUrl = "http://blockchain-dst:8555"
            ExternalWSUrl = "ws://127.0.0.1:8555"
            InternalWSUrl = "ws://blockchain-dst:8555"
