set fallback

import '../tools/lib/utils.justfile'

# Default: show available recipes
default:
    just --list

# Format all go files
fmt: ensure-golangci-lint
    golangci-lint fmt

# Run golangci-lint
lint fix="": ensure-golangci-lint
    golangci-lint run --output.text.path stdout {{ if fix != "" { "--fix" } else { "" } }}

mod-tidy: ensure-go
    go mod tidy

mod-download: ensure-go
    go mod download

test: ensure-go
    go test -v ./...

test-coverage:
    go test -v -coverprofile=coverage.out ./...

build:
    docker build -f Dockerfile -t executor:latest .

build-dev:
    docker build -f Dockerfile.dev -t executor:dev ..

clean:
    docker rmi executor:latest

clean-dev:
    docker rmi executor:dev
