with-expecter: true
inpackage: true

packages:
    github.com/smartcontractkit/chainlink-ccv/common/:
        config:
            dir: "{{.InterfaceDir}}"
        interfaces:
            CurseChecker: {}

