// Code generated by mockery v2.53.5. DO NOT EDIT.

package common

import (
	context "context"

	protocol "github.com/smartcontractkit/chainlink-ccv/protocol"
	mock "github.com/stretchr/testify/mock"
)

// MockCurseChecker is an autogenerated mock type for the CurseChecker type
type MockCurseChecker struct {
	mock.Mock
}

type MockCurseChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCurseChecker) EXPECT() *MockCurseChecker_Expecter {
	return &MockCurseChecker_Expecter{mock: &_m.Mock}
}

// IsRemoteChainCursed provides a mock function with given fields: ctx, localChain, remoteChain
func (_m *MockCurseChecker) IsRemoteChainCursed(ctx context.Context, localChain protocol.ChainSelector, remoteChain protocol.ChainSelector) bool {
	ret := _m.Called(ctx, localChain, remoteChain)

	if len(ret) == 0 {
		panic("no return value specified for IsRemoteChainCursed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, protocol.ChainSelector, protocol.ChainSelector) bool); ok {
		r0 = rf(ctx, localChain, remoteChain)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCurseChecker_IsRemoteChainCursed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRemoteChainCursed'
type MockCurseChecker_IsRemoteChainCursed_Call struct {
	*mock.Call
}

// IsRemoteChainCursed is a helper method to define mock.On call
//   - ctx context.Context
//   - localChain protocol.ChainSelector
//   - remoteChain protocol.ChainSelector
func (_e *MockCurseChecker_Expecter) IsRemoteChainCursed(ctx interface{}, localChain interface{}, remoteChain interface{}) *MockCurseChecker_IsRemoteChainCursed_Call {
	return &MockCurseChecker_IsRemoteChainCursed_Call{Call: _e.mock.On("IsRemoteChainCursed", ctx, localChain, remoteChain)}
}

func (_c *MockCurseChecker_IsRemoteChainCursed_Call) Run(run func(ctx context.Context, localChain protocol.ChainSelector, remoteChain protocol.ChainSelector)) *MockCurseChecker_IsRemoteChainCursed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.ChainSelector), args[2].(protocol.ChainSelector))
	})
	return _c
}

func (_c *MockCurseChecker_IsRemoteChainCursed_Call) Return(_a0 bool) *MockCurseChecker_IsRemoteChainCursed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCurseChecker_IsRemoteChainCursed_Call) RunAndReturn(run func(context.Context, protocol.ChainSelector, protocol.ChainSelector) bool) *MockCurseChecker_IsRemoteChainCursed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCurseChecker creates a new instance of MockCurseChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCurseChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCurseChecker {
	mock := &MockCurseChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
