with-expecter: true

dir: ./internal/mocks
outpkg: mocks

packages:
  github.com/smartcontractkit/chainlink-ccv/verifier/token/cctp:
    interfaces:
      AttestationService:
        config:
          filename: "mock_cctpAttestationService.go"
          mockname: "CCTPAttestationService"
  github.com/smartcontractkit/chainlink-ccv/verifier/token/lbtc:
    interfaces:
      AttestationService:
        config:
          filename: "mock_lbtcAttestationService.go"
          mockname: "LBTCAttestationService"

