with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
resolve-type-alias: false
packages:
    github.com/smartcontractkit/chainlink-ccv/verifier:
        config:
            dir: mocks
            outpkg: mocks
        interfaces:
            SourceReader:
