set fallback

import '../tools/lib/utils.justfile'

# Default: show available recipes
default:
    just --list

build-rc:
    docker build -f Dockerfile -t verifier:rc ..

build-dev:
    docker build -f Dockerfile.dev -t verifier:dev ..

publish-rc registry version:
    docker tag verifier:rc {{registry}}/chainlink-ccv-verifier:{{version}}-rc
    docker push {{registry}}/chainlink-ccv-verifier:{{version}}-rc

clean:
    docker rmi verifier:latest

clean-dev:
    docker rmi verifier:dev
