build:
    docker build -f Dockerfile -t verifier:latest .

build-dev:
    docker build -f Dockerfile.dev -t verifier:dev ..

clean:
    docker rmi verifier:latest

clean-dev:
    docker rmi verifier:dev

test:
    go test -v ./...

test-coverage:
    go test -v -coverprofile=coverage.out ./...

lint:
    golangci-lint run --fix

mod-tidy:
    go mod tidy

mod-download:
    go mod download
