with-expecter: true

dir: ./internal/aggregation_mocks
outpkg: aggregation_mocks

packages:
  github.com/smartcontractkit/chainlink-ccv/aggregator/pkg/common:
    interfaces:
      CommitVerificationStore:
      CommitVerificationAggregatedStore:
      Sink:
      AggregatorMonitoring:
      AggregatorMetricLabeler:
  github.com/smartcontractkit/chainlink-ccv/aggregator/pkg/aggregation:
    interfaces:
      QuorumValidator:


