root = ".."

[build]
cmd = "go build -o ./tmp/aggregator aggregator/cmd/main.go"
bin = "tmp/aggregator"
include_dir = ["app"]
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "testdata", ".git"]
