# syntax=docker/dockerfile:1.7
FROM golang:1.24.6-alpine
RUN go install github.com/air-verse/air@v1.62.0
WORKDIR /app
COPY aggregator/go.mod aggregator/go.sum ./
WORKDIR /
COPY protocol/ ./protocol/
COPY common/ ./common/
WORKDIR /app
ENV GOWORK=off
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build cd /protocol && go mod download
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build go mod download
COPY aggregator/air.toml ./
CMD ["air", "-c", "air.toml"]
