FROM golang:1.24.6-alpine
RUN go install github.com/air-verse/air@v1.62.0
WORKDIR /app
COPY aggregator/go.mod aggregator/go.sum ./
WORKDIR /
COPY protocol/ ./protocol/
COPY common/ ./common/
WORKDIR /app
RUN go mod download
COPY aggregator/air.toml ./
CMD ["air", "-c", "air.toml"]