set fallback

import '../tools/lib/utils.justfile'

# Default: show available recipes
default:
    just --list

build-rc:
    docker build -f Dockerfile -t aggregator:rc ..

build-dev:
    docker build -f Dockerfile.dev -t aggregator:dev ..

publish-rc registry version:
    docker tag aggregator:rc {{registry}}/chainlink-ccv-aggregator:{{version}}-rc
    docker push {{registry}}/chainlink-ccv-aggregator:{{version}}-rc

clean:
    docker rmi aggregator:latest

clean-dev:
    docker rmi aggregator:dev
