build:
    docker build -f Dockerfile -t aggregator:latest .

build-dev:
    docker build -f Dockerfile.dev -t aggregator:dev .

clean:
    docker rmi aggregator:latest

clean-dev:
    docker rmi aggregator:dev

proto:
    protoc --go_out=. --go-grpc_out=. ./proto/aggregator.proto

proto-lint:
    buf lint

proto-check: proto
    just proto
    if [ -n "$(git diff --name-only)" ]; then \
        echo "Error: Generated protobuf files are out of sync"; \
        echo "Run 'just proto' and commit the changes"; \
        exit 1; \
    fi

lint: proto-lint
    golangci-lint run --fix -c .golangci.yml

test:
    go test ./...