set fallback

import '../tools/lib/utils.justfile'

# Default: show available recipes
default:
    just --list

# Format all go files
fmt: ensure-golangci-lint
    golangci-lint fmt

# Run golangci-lint
lint: ensure-golangci-lint
    golangci-lint run --output.text.path stdout

mod-tidy: ensure-go
    go mod tidy

mod-download: ensure-go
    go mod download

test: ensure-go
    go test -v ./...

test-coverage: ensure-go
    go test -v -coverprofile=coverage.out ./...

build:
    docker build -f Dockerfile -t aggregator:latest .

build-dev:
    docker build -f Dockerfile.dev -t aggregator:dev .

clean:
    docker rmi aggregator:latest

clean-dev:
    docker rmi aggregator:dev
