name: Aggregator CI

on:
  push:
    paths:
      - 'aggregator/**'
  pull_request:
    paths:
      - 'aggregator/**'

defaults:
  run:
    working-directory: aggregator

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6 # v6
        with:
          cache: true
          go-version-file: aggregator/go.mod
          cache-dependency-path: |
            aggregator/go.sum

      - name: Install just
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v2.0.0

      - name: Install go-tools
        run: |
          just install-protoc
          just install-go-tools

      - name: Run lint
        run: just lint

      - name: Run proto-check
        run: just proto-check

      - name: Run tests
        run: just test