name: Build Dev Images

defaults:
  run:
    working-directory: build/devenv

on:
  push:
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Just
        uses: extractions/setup-just@v3
        with:
          just-version: '1.40.0'
      - name: Build Docker images with Just
        run: just build-docker-dev-ci
        env:
          DOCKER_BUILDKIT: 1
      - name: List built images
        run: docker images
