name: End-to-end CCV Test (EVM Testnets)

on:
  push:

defaults:
  run:
    working-directory: build/devenv

jobs:
  e2e:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu24.04-16cores-64GB
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Just
        uses: extractions/setup-just@v3
        with:
          just-version: '1.40.0'
      - name: Build Docker images with Just
        run: just build-docker-dev-ci
        env:
          DOCKER_BUILDKIT: 1
      - name: List built images
        run: docker images
      - name: Set up Go with module caching
        uses: actions/setup-go@v5
        with:
          go-version-file: build/devenv/go.mod
          cache: true
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Go dependencies
        run: |
          go mod download
      - name: Run CCV environment
        env:
          ETH_FUJI_PRIVATE_KEY: ${{ secrets.ETH_FUJI_PRIVATE_KEY }}
        run: |
          case "${{ inputs.network }}" in
            eth_fuji)
              PRIVATE_KEY=$ETH_FUJI_PRIVATE_KEY
              ;;
            *)
              echo "Unknown network: ${{ inputs.network }}"
              exit 1
              ;;
          esac
          cd cmd/ccv && go install . && cd -
          PRIVATE_KEY=${PRIVATE_KEY} ccv env.toml,env-fuji-fantom.toml
      - name: Run Soak Test
        working-directory: build/devenv/tests
        run: go test -timeout 2h -v -run TestSoak