name: Common CI

on:
  push:
    paths:
      - 'common/**'
  pull_request:
    paths:
      - 'common/**'

defaults:
  run:
    working-directory: common

jobs:
  common-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: common/go.mod

      - name: Install just
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v2.0.0

      - name: Install go-tools
        run: |
          just install-protoc
          just install-go-tools

      - name: Run proto-lint
        run: just proto-lint

      - name: Run proto-check
        run: just proto-check