name: Common CI

on:
  push:
    paths:
      - 'common/**'
  pull_request:
    paths:
      - 'common/**'

defaults:
  run:
    working-directory: common

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: common/go.mod

      - name: Install just
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v2.0.0

      - name: Install protoc
        run: |
          PROTOC_VERSION="32.0"
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
          sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc
          sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local 'include/*'
          rm protoc-${PROTOC_VERSION}-linux-x86_64.zip
          protoc --version

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Install buf
        uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run proto-lint
        run: just proto-lint

      - name: Run proto-check
        run: just proto-check