name: Component Tests

on:
  pull_request:

jobs:
  executor-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Lint and Test Executor
        uses: ./.github/actions/lint-test-component
        with:
          dir: executor
          go-mod-path: executor/go.mod
          go-sum-path: executor/go.sum
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

  verifier-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Lint and Test Verifier
        uses: ./.github/actions/lint-test-component
        with:
          dir: verifier
          go-mod-path: verifier/go.mod
          go-sum-path: verifier/go.sum
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

  root-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Lint and Test Verifier
        uses: ./.github/actions/lint-test-component
        with:
          dir: root
          go-mod-path: go.mod
          go-sum-path: go.sum
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

