name: Devenv Tidy
on:
  push:

defaults:
  run:
    working-directory: build/devenv

jobs:
  devenv-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6 # v6
        with:
          go-version-file: build/devenv/go.mod
      - name: Verify go.mod and go.sum
        run: |
          go mod tidy
          if ! git diff --exit-code -- go.mod go.sum; then
            echo "❌ go.mod or go.sum has uncommitted changes after go mod tidy"
            echo "Please run: go mod tidy"
            git diff -- go.mod go.sum
            exit 1
          fi