name: Protocol Tests

on:
  push:
    paths:
      - 'protocol/**'
  pull_request:
    paths:
      - 'protocol/**'

defaults:
  run:
    working-directory: protocol

jobs:
  protocol-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6 # v6
        with:
          go-version-file: protocol/go.mod

      - name: Install just
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v2.0.0

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
        with:
          version: latest
          working-directory: protocol
          args: --help # Just install, don't run yet

      - name: Run lint
        run: just lint

      - name: Run tests
        run: just test
