name: Verifier Tests

on:
  push:
    paths:
      - 'verifier/**'
      - 'protocol/**'
  pull_request:
    paths:
      - 'verifier/**'
      - 'protocol/**'

defaults:
  run:
    working-directory: verifier

jobs:
  verifier-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6 # v6
        with:
          cache: true
          go-version-file: verifier/go.mod
          cache-dependency-path: verifier/go.sum

      - name: Populate go envs
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
          echo "GOCACHE=$(go env GOPATH)/build" >> $GITHUB_ENV

      - name: Cache Go toolchain artifacts
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.GOBIN }}
            ${{ env.GOCACHE }}
          # hashFiles paths are repo-root relative (not affected by working-directory)
          key: chainlink-ccv-gotools-${{ runner.os }}-${{ hashFiles('tool-versions.env') }}
          restore-keys: |
            chainlink-ccv-gotools-${{ runner.os }}-

      - name: Install just
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v2.0.0

      - name: Install go-tools
        run: just install-go-tools

      - name: Run lint
        run: just lint

      - name: Run tests
        run: just test
